### ISSUE TITLE
Uppdatera Groovy till senaste version

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#107]

**Comment by cheijken** [comment]
senaste versionen nu är 2.4.0

**Comment by cheijken** [comment]
Fixat.
Testa genom att bygga ''feature/107_update_groovy'' på test och kontrollera att http://test.lagrummet.se fungerar.

**Comment by kamidev** [comment]
Det funkar att bygga på test. Men jag tror vi borde köra en komplett version av testerna (med sök påslaget) för säkerhets skull.

**Comment by cheijken** [comment]
Kör regressionstesterna och det är ok. :smile:
