### ISSUE TITLE
Bemyndigande (och andra egenskaper) visas i service men inte i lagrummet

### ISSUE THREAD

**Issue by mtiasp** [rinfo/lagrummet.se#113]
Dokument som har en korrekt angiven egenskap av typen "bemyndigande" visas i service men inte i lagrummet. Varför inte?

I nedanstående exempel används <http://rinfo.lagrummet.se/publ/emfs/2011:39> från http://testfeed.lagrummet.se/feed.atom.

I service (http://service.test.lagrummet.se/ui/#/publ/emfs/2011:39/data.json) finns många relationer/egenskaper inklusive "bemyndigande" med för http://rinfo.lagrummet.se/publ/emfs/2011:39:

![emfs_2011_39_service](https://f.cloud.github.com/assets/2376280/2074804/2a98446e-8d81-11e3-97a6-1c1b8af7dc55.png)

I lagrummet (http://test.lagrummet.se/rinfo/publ/emfs/2011:39) finns dock inte dessa relationer och egenskaper med:

![emfs_2011_39_lagrummet](https://f.cloud.github.com/assets/2376280/2074811/3d14e1ce-8d81-11e3-8995-e2a7be63baa6.png)

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#205
