### ISSUE TITLE
Få in feedback på beta-release via webben

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#124]
Kan vi återanvända/modifiera befintlig kontaktsida i lagrummet?

**Comment by jeldeklint** [comment]
Kontaktsidan är ju en mall-typ, bör bara vara att skapa en ny sida med den mallen med lämplig text. Hade varit bra om det gick att konfigurera `subject`, osäker på om det går idag.

**Comment by kamidev** [comment]
Vi bör undersöka vilken SMTP-konfiguration som krävs för att kunna få in feedback under nästa release.

**Comment by kamidev** [comment]
Se även issue #287

**Comment by cheijken** [comment]
Har lite svårt att se skillnad mellan denna och #287.

**Comment by kamidev** [comment]
Den här handlar om att vi behöver någotbra sätt att få in feedback: vad ska vi skriva för instruktion till användaren, vem läser feedbacken, vilken mejl använder vi etc. D v s lösa hela problemet. Oavsett om vi använder kontaktformuläret eller inte. 

Det andra ärendet var en specifik buggrapport på formuläret. Berodde den bara på avsaknaden av en SMTP-server är det kanske fixat nu?

**Comment by lalindqv** [comment]
Som myndighet kanske man också måste diarieföra alla inkomna synpunktern och och också svara på dem. Vad säger @helelun ?

**Comment by jeldeklint** [comment]
Efter som de kommer in till ett mailkonto hanterat av `DV` så borde väl diarieförningen vara OK redan? @helelun svarar redan på synpunkterna såvittjagvet.

**Comment by helelun** [comment]
Synpunkter på betasök vill vi få in till en befintlig brevlåda avsedd för just detta. Vi kommer ha en text på sajten där det framgår att vi kanske inte svarar brevskrivaren personligen, att vi är tacksamma för och tar hand om alla synpunkterar och att vi lite då och då avser publicera frågor & svar på webbplatsen. Vi kan också lägga ett autosvar på brevlådan med motsvarande innehåll. 

Mejl till lagrummet.se diarieförs inte. Vi besvarar alla mejl enligt de riktlinjer som finns finns på webbplatsen. Mejlen gallras efter tre månader. Detsamma kommer att gälla för den särskilda brevlådan för återkoppling på betasök.
