### ISSUE TITLE
Länkikon hamnar fel på vissa ställen på olika redaktionella sidor

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#135]
Exempel i IE10:
http://beta.lagrummet.se/lar-dig-mer/ordlistan-a-o

![135 lnkikon hamnar fel](https://cloud.githubusercontent.com/assets/6142669/2969803/ed630d3a-db51-11e3-836f-7c48266822cb.png)

http://beta.lagrummet.se/hit-vander+du+dig/myndighetersansvar

![135 lnkikon fel](https://cloud.githubusercontent.com/assets/6142669/2969898/4e1a313e-db53-11e3-99bc-c9d1d8f1330a.png)

Drabbade sidor ligger under vänstermenyns rubriker Hit vänder du dig resp. Lär dig mer. Sidorna under rubriken Rättsinformation, som alla länkar till rättskällor, verkar inte ha detta fel.

**Comment by lalindqv** [comment]
Problemet går att återskapa och lösa  enligt beskrivning ovan.
Valle, 2.1.5, IE 10
