### ISSUE TITLE
Admin sparar tidigare lösenord

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#155]
I lösenordsfältet kan jag genom att dubbelklicka i det tomma fältet se lösenorden till de senast upplagda användarna. Mina egna lösenord och tidigare upplagda användares lösenord syns inte.

**Comment by evajerr** [comment]
OK.
Jag testade att lägga upp nya användare efter varandra och har inte lyckats få upp något föregående lösenord. Så det fungarar enligt mej om jag fattat rätt.

Hade önskat en inklippt bild som visade hur felet uppstår istf enbart textuella beskrivningar. Det är mindre risk för missförstånd.
