### ISSUE TITLE
Flera titlar för samma dokument kan hittas

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#157]
Underliggande data har verkligen har flera titlar. Det finns ingen verksamhetsmässigt säkert sätt att veta vilken vi ska välja. Finns det en tillräckligt bra kompromisslösning?

Det här slår igenom i lagrummet.se, där högerspalten på en dokumentsida kommer att lista flera titlar.

**Comment by kamidev** [comment]
Flyttar till RDL

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#158

**Comment by kamidev** [comment]
Flyttar tillbaka hit. Detta ärende handlar bara om presentationen.

**Comment by cheijken** [comment]
Denna är möjligen löst i #360. Den kontrollerar om det är möjligen flera titlar och växlar då till att visa identitet i stället för titel. Den lösningen kan givetvis funderas på.

**Comment by jeldeklint** [comment]
den borde vara ~done se rinfo/rdl#146
ska skriva testinstruktioner, det är inte helt trivialt.

**Comment by jeldeklint** [comment]
För att testa kolla ändringar undersök ändringsposterna för en förordning som ändras av `2007:636` t.ex. BrB `1962:700`. Öppna "Visa alla NNN ändringsförfattningar" skolla ner tills ändringen för `2007:636` dyker upp. Det ska visas en titel, "Förordning (2007:636) om ikraftträdande av lagen (2005:688) om ändring i brottsbalken"

**Comment by kamidev** [comment]
Testat enligt ovan efter att ha checkat in föreslagen fix för https://github.com/rinfo/rdl/issues/146. Men får fortfarande en lista med flera titlar för Förordning (2007:636).

**Comment by kamidev** [comment]
Testat enligt ovan efter att ha checkat in ny fix för rinfo/rdl#146. Ger förväntat resultat på demo, se skärmbild: 

![skarmavbild 2015-03-04 kl 13 40 55](https://cloud.githubusercontent.com/assets/1655/6483703/40a0c406-c274-11e4-9899-477d17b68a2f.png)

**Comment by lalindqv** [comment]
Har kollat, men frågan är var problemet ligger. Är felet att källan som har fler än 1 titel, eller att RDL-insamlingen accepterar fler än en titel eller är felet att presentationen är knas?

**Comment by kamidev** [comment]
Se problembeskrivningen överst i ärendet: "Underliggande data har verkligen har flera titlar."
