### ISSUE TITLE
Ange i admin vilken rättskälla som är borttagen

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#171]
När jag tar bort en rättskälla får jag beskedet "Rättskälla 49 borttagen". Siffran bör ersättas med namnet på den borttagna rättskällan.

Jfr motsvarande besked vid upplägg av ny rättskälla "Rättskälla X-myndighetens författningssamling XxFS skapad".

**Comment by jeldeklint** [comment]
För att testa, I Admin, ta helt enkelt bort en rättskälla. I meddelandet efter rättskällan är borttagen ska det nu stå, "rättkällansnamn (rubrik / underrubrik)"

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se
