### ISSUE TITLE
Synonym i admin kan inte raderas

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#172]
[Sökverktyg, hantera synonymer]. Poster upplagda i synonymlistan kan inte raderas (varken gamla eller nya). Jag klickar på radera-ikonen och därefter OK på frågan "Är du säker på att du vill ta bort denna synonymen?". Sedan händer inget mer. Har provat att efter OK klicka på Spara ändringar.

(När denna issue hanteras, passa på att också ta bort ändelsen -en i dialogrutan så att det bara står "synonym").

**Comment by jeldeklint** [comment]
Åtgärdat stavningen lite snabbt. Observera att man kan behöva tömma cachen (eller tvinga en uppdatering av `admin.js`) för att det ska slå igenom

**Comment by kamidev** [comment]
Verifierad mot test.lagrummet.se

**Comment by helelun** [comment]
Kan nu ta bort borde befintliga och nya synonymer.
