### ISSUE TITLE
Redigerad synonym beter sig instabilt vid fritextsökning

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#173]
[Sökverktyg, hantera synonymer]. Redigerade synonymer är sökbara även med gamla uppgifterna. (De gamla uppgifterna syns inte längre i Admin). 
Exempel 1: redigerade synonymen med populärnamn "populär-test" är sökbar på sajten men det är också synonymens gamla namn "testpoppis". 
Exempel 2: även ett redigerat formellt namn, som till exempel kan vara ett annat begrepp eller namnet på en lag, spökar på sajten när man söker flera gånger eller bara refresh.ar.

**Comment by kamidev** [comment]
Är detta fortfarande ett problem? @helelun, går det att återskapa?

**Comment by helelun** [comment]
Jag kan inte återskapa de två felen. Testat på beta.

**Comment by helelun** [comment]
Kan inte återskapa felet att redigerat populärnamn även är sökbart på sitt tidigare namn.

Befintliga synonymer där jag ändrar det formella namnet fungerar.
Undantag: befintliga synonymen populär-test får jag inte träff på fastän jag redigerat det formella namnet till begrepp som finns på webbplatsen. 

Att lägga upp nya synonymer och därefter ändra antingen populärnamnet eller formella namnet fungerar. Även synonymer som innehåller bindestreck (så det är inte det som är fel i populär-test). 

Noterar att för synonymer som inte ger träff på webbplatsen får jag heller inte meddelandet om att min sökning också skett på annat begrepp. Är det förväntat beteende?

**Comment by lalindqv** [comment]
Allts tycks fungera som förväntat.

Ändrade på Valle
poplär-test författningssamlingsförordning (1999:175) 
till
populär-test synpunkter

Sökning på "synpunkter" och "populär-test" ger i princip samma resultat i Valle:
![c1](https://cloud.githubusercontent.com/assets/9251555/5935731/4cc7e1c6-a6de-11e4-9e11-193ad6ea35b7.PNG)
![c2](https://cloud.githubusercontent.com/assets/9251555/5935734/571e78ce-a6de-11e4-83aa-ac0fe3086920.PNG)


Sökning på populär-test kopplat till författningssamlingsförordning (1999:175)
ger ingen och ska inte ge träff i Ville, Valle, Viktor eftersom sökning inte sker i RDL.

På Betan verkar sökning ske i RDL och där får man träff på synonymen populär-test:
![c3](https://cloud.githubusercontent.com/assets/9251555/5935767/c95ce6aa-a6de-11e4-8a2a-82971d133eaf.PNG)

**Comment by lalindqv** [comment]
Om man inte får träff på söksträngen eller dess synonym får man inte meddelande om att sökningen även skett på synonymen.

Varför lägga upp synonymer till något som inte finns ?

**Comment by kamidev** [comment]
Ja, det är förväntat beteende att inte få något svar. Om man inte får någon träff på synonymen. På testmaskinerna söker vi just nu bara på det redaktionella och då ger synonymerna ibland inga träffar.

**Comment by helelun** [comment]
Min eventuella förväntan var att jag skulle få veta att sökningen även skett på synonymen. Vare sig jag fått träff eller inte. Då har man som användare i alla fall fått med sig det aktuella begreppet.  

Gjorde en jämförelse med beta. Sökning på synonymen skilsmässa ger träff på äktenskapsskillnad. Detta fungerar så länge jag är på Alla rättskällor eller har avgränsat till källa som innehåller begreppet. Avgränsning på Myndigheter ger ingen association då det (idag) inte finns någon föreskrifter som innehåller begreppet. 

Konstaterar att jag i nuläget inte ska förvänta besked om att sökning skett på synonym.

**Comment by helelun** [comment]
Synonymen populär-test verkar ha fått fnatt endast på valle. Allt annat fungerade.

**Comment by kamidev** [comment]
Har förväntat beteende i nuläget. Vi bör fundera vidare över om det behövs bättre feedback när användaren inte får träff.
