### ISSUE TITLE
inkludera "wildcard" i sökning på lagrummet

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#176]
Vi borde lägga till ett "osynligt" wildcard eller liknande i sökningen från lagrummet.
Då skulle sökresultatet för `rättsinfo` automatiskt gå från
![image](https://cloud.githubusercontent.com/assets/579622/3552478/022342fc-08f8-11e4-961b-c72edf3145ac.png)

till
![image](https://cloud.githubusercontent.com/assets/579622/3552473/eb100d52-08f7-11e4-98bd-dac2ccea5f45.png)

**Comment by jeldeklint** [comment]
Bra läsning här är; http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/partial-matching.html speciellt om "ngrams"

**Comment by jeldeklint** [comment]
Således bör den här förpassas till RDL och ett större omtag av elasticsearch frågorna där

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#155
