### ISSUE TITLE
Var tar rättsfallen vägen när man söker på t.ex. SFS nummer?

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#191]
En bild säger mer än tusen ord?
![screenshot 2014-10-14 13 45 55](https://cloud.githubusercontent.com/assets/579622/4628536/8c37fefc-5398-11e4-8d20-575ca5797e19.png)

Det finns ju uppenbarligen träffar? är det för att de ligger så pass långt ner?

**Comment by jeldeklint** [comment]
Även detta borde _helst_ åtgärdas på RDL sidan i svaret från elasticsearch

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#154

**Comment by jeldeklint** [comment]
lämpligt att ärendet finns kvar för test / verifiering dock. Tror inte @lalindqv är så sugen på att läsa typ json eller xml som test :)

**Comment by jeldeklint** [comment]
ah, du klonade hela ärendet. bra. :)

**Comment by lalindqv** [comment]
Är detta mail automatgenererat elller har du Jonas angett min Sogeti-mailaaress ?

**Comment by kamidev** [comment]
Pröva samma sökningar igen.

**Comment by lalindqv** [comment]
Se kommentar rinfo/rdl#154

**Comment by cheijken** [comment]
Stänger.
Testat genom vanlig sökning. ex 1999:175.

**Comment by lalindqv** [comment]
OK
