### ISSUE TITLE
Borttag av synonymer fungerar inte i Internet Explorer 10

### ISSUE THREAD

**Issue by daniby** [rinfo/lagrummet.se#194]
CasperJS-testerna går igenom korrekt, det fungerar fint att ta bort en synonym i Google Chrome men inte i Internet Explorer 10.

Detta gäller efter fix av: #187
Dupliceras av #172

**Comment by kamidev** [comment]
Verifierad mot test.lagrummet.se och IE10

**Comment by lalindqv** [comment]
Borttag av synonym fungerar i IE 11.
Borttag av synonym fungerar i emulerat IE 10 och IE 5
(Knapparna "Edit" och "Ta bort" syns varken i Chrome 40 eller Firefox 35)

**Comment by jeldeklint** [comment]
lustigt, i Chrome `39.0.2171.95 (64-bit)` och i Firefox `36.0a2 (developer)` på mac finns knapparna.

**Comment by lalindqv** [comment]
Jag kan visa - fast det är ju inget att visa .

**Comment by jeldeklint** [comment]
Verkar ha något med windows att göra, ändrar man zoom-nivå:n dyker de upp och sedan försvinner igen periodiskt. På motsvarande browsers på mac händer det inte.. inget jag sett förut..

**Comment by jeldeklint** [comment]
det skulle kunna ha något att göra med hur DPI hanteras, om det är mixat relativa och absoluta storlekar

**Comment by jeldeklint** [comment]
Det här borde inte vara något nytt - inga ändringar i admins css som kan påverka har gjorts
