### ISSUE TITLE
"dynamiska" sökresultatet och det "statiska" ser olika ut

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#220]
resultatsidorna för söken ser lite olika, bland annat finns inte skrivutknappen på den "dynamiska" och vi visar vilket sökord som användes olika.

![screen shot 2014-11-13 at 11 49 57](https://cloud.githubusercontent.com/assets/579622/5027093/8ac75130-6b2b-11e4-8e6e-d3b135f9f489.png)

![screen shot 2014-11-13 at 11 49 45](https://cloud.githubusercontent.com/assets/579622/5027096/8bf1de68-6b2b-11e4-8e56-6362762789ef.png)

**Comment by cheijken** [comment]
Incheckad och klar.
Körs på valle och demo.
Testa genom att söka (utan att trycka enter) och sedan trycka enter. Båda resultaten skall vara identiska.
