### ISSUE TITLE
Söksträng måste vara exakt (?)

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#222]
Sökning på "räksmörgås" ger ingen (0) träff.
Sökning på "räksmörgåsar" ger en (1) relevant träff.

Jag hade förväntat mig att "räksmörgås" skulle ge lika många eller fler träffar än "räksmörgåsar".

Testmiljö: http://test.lagrummet.se

**Comment by kamidev** [comment]
Flyttar den här till RDL

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#156
