### ISSUE TITLE
Söksträngen feltolkas och delas upp

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#226]
Om tecknet ":" (kolon) används i en söksträng feltolkas det och gör att säkning sker på tecken före __och__efter ":" 
Exempel: Sökning på 1998:144 ger träff på dokument som innehåller både 1998 och 144.

Förväntat att sökningen sker på den exakta strängen "1988:144"

**Comment by jeldeklint** [comment]
bör hanteras i frågorna till elasticsearch, kolla på typ `analyzers / tokenizers`

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#153

**Comment by lalindqv** [comment]
Fungerar riktigt bra: 
sökning på "år:" ger inte fler träffar än "år:
sökning på "år" eller "år:" ger lika många träffar. 
sökning på exakt beteckning ger träff.
