### ISSUE TITLE
lagrummets sidfot ser sned ut.

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#227]
Sidfoten ser tämligen sned ut i lagrummet. sista kolumnen borde höger justeras och den mitten, ja. centreras.
Detta har inget att göra med den nya temporära startsidan

**Comment by jeldeklint** [comment]
genom att ändra bredden till 33% från 30% ser det lite bättre ut, utan en massa bråk.
![screenshot 2015-01-08 16 43 59](https://cloud.githubusercontent.com/assets/579622/5665059/bf7e8244-9755-11e4-8df3-879908ba2d15.png)

Bästa vore väl att lösa det med en flexbox, men äldre browsers har inte stöd för det..

**Comment by jeldeklint** [comment]
En sak som slog mig, i Admin så kan man ju lätt tro att det går att lägga till kategorier i sidfoten, vilket givetvis går. Men, sidfoten är stilmässigt anpassad till att varje rad i sidfoten har tre kolumner; så det ser rätt hemskt ut att lägga till en extra kolumn i sidfoten.

**Comment by jeldeklint** [comment]
Jag lade in fixen direkt på develop, borde trilla ut på demo.lagrummet.se snart

**Comment by kamidev** [comment]
Verifierad på lagrummet.se
