### ISSUE TITLE
Webbkartan listar sidor som inte är publicerade

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#229]
Webbkartan listar, utöver sidor som ärpublicerade, även sidor som har status: Utkast, Avpublicerad, Publiceras Senare.
(Om man klickar på länken så visas helt korrekt "sidan kunde inte hitas" )

Jag förväntar mig att webbkartan bara listar sidor som är publicerade.

Krav-ID:74

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se

**Comment by evajerr** [comment]
Fungerar i Happy Flow. Har testat Utkast, Avpublicera och Publiceras senare.

Publiceras senare fungerar inte om sidan en gång varit publicerad. Då ligger den kvar  både i trädet och i Webbkartan. De ska bort enligt mej. Se felrapport 362.
