### ISSUE TITLE
Kan inte skapa mellanrum mellan stycken i beskrivande text rättskällor

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#232]
Radmat i beskrivande text i admin/hantera rättskällor blir inte radmat på betasajten. Se till exempel Förarbeten/Departementsserien (Ds).

Meningen som börjar med "Länken går till en söksida" ska vara nytt stycke.

**Comment by jeldeklint** [comment]
jag har råkat commita fixen till den här på #230 istället, klantigt! commiten har id 7cdbefd

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se

**Comment by lalindqv** [comment]
Fungerar bra. 
Valle version 2.1.5, IE 10
![capture](https://cloud.githubusercontent.com/assets/9251555/5934137/32292e32-a6cb-11e4-8c19-6a7f7ce69b7e.PNG)
