### ISSUE TITLE
Förbättra loggning vid fritextsökning i lagrummet.se

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#238]
Lagrummet loggar i princip ingenting, förutom exceptions (vilka ofta ignoreras eller returnerar en 404:a istället för att hanteras/kastas vidare, så de loggas bara när de kastas ut till system.err) vilket gör felsökning, övervakning osv. svårt.

en snabb sökning i kodbasen visar på att det loggas på 5 ställen, i två olika filer.

**Comment by kamidev** [comment]
Ser ut som ett bra sätt att fånga exceptions.

**Comment by cheijken** [comment]
Efter ytterligare bollande, så är min åtgärd följande.
Fokus på sökningen, men ej utökad sökning.
Spåra möjliga exeptions, som fångas loggas och hanteras. 
Ytterligare trace/info log läggs till för att spåra sökord, antal träffar och söktid.
Om övrigt, så placera i nytt ärende. :)

**Comment by kamidev** [comment]
OK. Gjorde titeln på detta ärende mer specifik och fixar ett mer generellt till nästa release.

**Comment by cheijken** [comment]
Loggar sökord och tider och fel lite bättre. Svårt att lägga på detta i efterhand, utan vetskap om vilka fel som brukar inträffa. Tror det blev ganska bra i alla fall. 
Klar!

**Comment by cheijken** [comment]
Testa genom. 
Installera feature feature/238_benchmark_and_log på test.
SSH:a till maskinen och öppna loggen. "tail -100f /opt/tomcat/log/lagrummet.log"
Öppna http://test.lagrummet,se/search?cat=Alla&query=katt&searchSubmit=S%C3%B6k
Kolla att loggen ser bra ut: (Skall finnas med timing)
Öppna http://localhost:8080/lagrummet.se/rinfo/publ/sfs/2008:1049/konsolidering/2008-12-31
Kolla loggen (Timing)
http://localhost:8080/lagrummet.se/rinfo/publ/sfs/2008:1049/konsolidering/2008-12-30
Kolla loggen (Kolla fel i loggen
