### ISSUE TITLE
Varje sida får två URL

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#239]
Varje sida tycks ha två URLer. Båda dessa URL visar rätt sida, men jag undrar om detta kan vara ett tecken på ett allvarligare problem.

Som exempel ser sida "Rättspraxis" ut ¨å här i  Admin:
![bug url1](https://cloud.githubusercontent.com/assets/9251555/5104363/97bbd086-6fe1-11e4-8803-5d233d5e45f1.PNG)

Sidan finns tillgänglig både på htttp://ville.lagrummet.se/rattsinformation/rattspraxis ...
Detta är den URL som presenteras trädstrukturen och som användaren klickar op

![bug url2](https://cloud.githubusercontent.com/assets/9251555/5104382/c14c1d20-6fe1-11e4-8722-5ddb055f8d1c.PNG)

Och som förväntat på htttp://ville.lagrummet.se/rattspraxis ... ...
Här måste jag själv ange adressen manuellt i browsern.

![bug url3](https://cloud.githubusercontent.com/assets/9251555/5104387/d1b72f74-6fe1-11e4-9ebc-4f7fa35c7ded.PNG)

**Comment by jeldeklint** [comment]
Ett sätt att åtgärda detta är att nysta upp trädet vid sidrendering, och helt enkelt kräva att sökvägen föräldern stämmer också. I fallet med "Rättspraxis" ovan så har sidan en förälder som har sökvägen "rattsinformation".

Det skulle, för att minska risken för problem med eventuella bokmärken m.m; om url-en saknar korrekt förälder, helt enkelt nysta upp och göra en 301:a (flytten är permanent) till korrekt url.

givetvis ska vi se till att alla länkar är korrekta på lagrummet..

**Comment by jeldeklint** [comment]
Visar nu hela url:en till en sida när man redigerar dem på admin.

**Comment by kamidev** [comment]
Verifierad på test och demo.

**Comment by lalindqv** [comment]
Ser bara en URL.
Går inte att skapa två sidor med samma URL.
Allt tycks OK.
