### ISSUE TITLE
Måste klicka två gånger för att spara, spara utkast, publicera och uppdatera

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#240]
Mycket irriterande då knapparna samidigt flyttar sig.
Inför klick1 på "spara utkast"
![bugg 2click1](https://cloud.githubusercontent.com/assets/9251555/5106059/4e04304c-6ff4-11e4-8853-4901fee1fa22.PNG)

Efter att ha klickat på spara utkast en gång
![bugg 2click2](https://cloud.githubusercontent.com/assets/9251555/5106064/5b1e1e1e-6ff4-11e4-9d58-36f9bf898466.PNG)

**Comment by kamidev** [comment]
Testad IE 10 och IE11 efter uppdateringen av TinyMce. Knapparna flyttar fortfarande runt ibland. Men det räcker med ett klick.

**Comment by lalindqv** [comment]
Knapp "Uppdatera" - måste klicka två gånger för att uppdateringen ska sparas..

Knapp "Spara utkast" - ett klick räcker.
Knapp "Spara" - ett klick räcker
Knapp "Publicera" - ett klick räcker
Knapp "Avpublicera" - ett klick räcker
Knapp "Förhandsgranska" - ett klick räcker

**Comment by jeldeklint** [comment]
I vilken browser har du testat?
Kan ej återskapa i IE 10.0.23 (browser mode: IE10 document mode: standards) under win 7 iaf. Har du tömt ev. cache och dyl.?

**Comment by lalindqv** [comment]
Fel Spara utkast - måste klicka två gånger.

IE 11

**Comment by lalindqv** [comment]
Testar i IE 10:
Spara utkast - ett klick.
Uppdatera - ett klick.

Stänger därför denna rapport.
