### ISSUE TITLE
Sidan "Sidor" - varför poppar den upp ?

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#242]
Då man tar bort en sida så visas sidan "sidor":

![bug sidor](https://cloud.githubusercontent.com/assets/9251555/5121229/ba6a5914-708f-11e4-89b5-beed0e5339af.PNG)

Sidan "sidor" känns som en väldigt trevlig funktion, men hur sjutton är det tänkt att man ska nå den egentligen ?
Den tycks sakna en egen länk.

Testmiljö: Ville. lagrummet version 0.8.7.

**Comment by jeldeklint** [comment]
Den dyker upp för att efter ett borttag gjorts så redirectas man explicit till `action: list` på `page`-controllern istället för, exempelvis admin:s  startsida eller så. Skulle kunna varit så sedan controllern antagligen genererades av grails.
