### ISSUE TITLE
Avpublicering av sida med status "utkast, version gäller" möjlig

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#243]
Knapp för Avpublicering av sida med status "utkast, version gäller" finns tillgänglig.
Om man klickar på Avpublicera hade jag förväntat mig att den publicerade sidan blir avpublicerad.
Jag förväntar mig att det inte går att avpublicera utkast.
Jag förväntar mig att det går att avpublicera publicerade sidor.

Se nedanstående. Sidan "Lägg till rubrik här " har 
status "Utkast"
status "Utkast, version gäller och visas" enligt symbolen i trädet till vänster.

![bug avpublicera utkast](https://cloud.githubusercontent.com/assets/9251555/5123680/5edb7eec-70ae-11e4-88af-ab7a0112d5bd.PNG)

**Comment by lalindqv** [comment]
Förtydligande:
För att en sida ska kunna ha status "Utkast, publicerad version gäller" måste den först vara Publicerad. Sedan måste redaktör spara den som utkast.

Fel 1: Ett klick på Knapp "Avpublicera" avpublicerar inte den publicerade revisionen som förväntat.
Fel 2a: Ett klick på Knapp "Avpublicera" skapar en ny revision av utkastet. 
Fel 2b: Man kan tro att en ny revision av utkastet (genom att klicka på Avpublicera) innebär att alla ändringa har sparats. Så är inte fallet.

Knappen  "Avpublicera" borde inte vara möjlig att använda för sidor med status "Utkast, publicerad version gäller" .
Knappen  "Ta bort" borde inte vara möjlig att använda för sidor med status "Utkast, publicerad version gäller" .

Frågan är då hur man ska hantera det scenario som innebär att man vill avpublicera aktuell sida och , samtidigt ha ett utkast som ska publiceras senare, dvs publicera r1 - > publicera ingenting -> publicera r2

**Comment by jeldeklint** [comment]
samma här som i #291 Avplublicera visas om sidan är "huvud-version" och har något barn som är publicerad. Fråga inte varför.

**Comment by jeldeklint** [comment]
Sidan i sig har förövrigt inte så mycket med vilken ikon som visas i trädet, dvs. en sida kan inte ha statusen "Utkast, publicerad version gäller".
Dock kan man säga att sid-trädet är i status "Utkast, publicerad version gäller" det betyder att det finns en publicerad version, men det är ett utkast som är "huvud-version". Men det sparas ingenstans utan räknas ut vid rendering.

**Comment by lalindqv** [comment]
Föreslår att denna ses som ett duplikat till #291 
Föreslår att denna rapport stängs.

**Comment by lalindqv** [comment]
Knapp avpublicera syns ej för utkast.
