### ISSUE TITLE
Publicerade sidor går att ta bort

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#245]
Om en sida har status "Utkast, version gäller och visas" går den att ta bort genom att klicka på "ta bort".

Det ska ej vara möjligt att ta bort sidor som tidigare har varit publicerade. Detta bryter mot krav 103.

Hur återskapa:
1. Publicera en sida
2. Redigera sidan och spara ett utkast så att status blir "Utkast, version gäller och visas" , vilka har denna symbol:  ![icon utkast version galler och visas](https://cloud.githubusercontent.com/assets/9251555/5124558/56096eea-70b9-11e4-8eed-6f6a5909356d.jpg). Enklast genom att välja ett från-datum några dagar framåt.

3. Klicka på "Ta bort". Klicka "OK"
4. Hela sidan och alla dess revisioner är borta.

Roll: Administratör / Admin
Testmiljö: Ville
Version: 0.8.7

**Comment by jeldeklint** [comment]
Mycket riktigt, det görs ingen validering mot sid-status innan borttag görs på serversidan. och Editors har tilllåtelse också.

Börjar med att dra in behörigheten för Editors samt tvinga sidan att vara opublicerad.

**Comment by jeldeklint** [comment]
Hur vi ska avgöra om sidan någonsin varit publicerad är inte helt uppenbart från de statusarna som används.

**Comment by jeldeklint** [comment]
åååååh, hittade just en "tilldelning istället för jämförelse"-bugg i koden som avgör om en sida är publicerad eller ej.

**Comment by jeldeklint** [comment]
sådär, verkar fungera nu. 
6d9f027 kan ha ställt till med något, om det har funnits något "fungerar p.g.a fel"-ställe för publicerings-status. la till ett par lama enhetstest för om status är "publicerad".

**Comment by jeldeklint** [comment]
Ok, Redaktörer skulle också få ta bort utkast som ej publicerats

**Comment by jeldeklint** [comment]
@helelun @lalindqv ska jag göra det möjligt att radera utkast _efter_ sidan har publicerats, dvs sådana revisioner som inte har varit publicerade? Kräver ett par kodändringar med det är inget stort.

**Comment by lalindqv** [comment]
Ja, jag tycker att man ska kunna radera utkast.

**Comment by kamidev** [comment]
Instämmer med @lalindqv

**Comment by jeldeklint** [comment]
Kollade lite närmre, det är "master"-revisionen som ej kan tasbort i status `utkast`. 
För att den innehåller referenser till alla tidigare revisionerna. "Barn" till den som är i status `utkast` går att tabort. Känns som att det nog är förväntat beteende?

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se. Publicerade sidor går intel längre att ta bort.

**Comment by lalindqv** [comment]
eVerkar bara kunna ta bort sidor som ej varit publicerade - OK:
