### ISSUE TITLE
Möjligt att olika sidor sparas med samma URL

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#248]
rattspraxis
![bug rp1](https://cloud.githubusercontent.com/assets/9251555/5125060/2351748c-70c0-11e4-8519-d97e756cc72d.PNG)

och Rättspraxis
![bug rp2](https://cloud.githubusercontent.com/assets/9251555/5125063/2dbd0d8c-70c0-11e4-832b-9eb4d54acf43.PNG)

Den tidigare sidan verkar dock inte skrivas över av den nya (här har jag klickat på rattspraxis):
![bug rp3](https://cloud.githubusercontent.com/assets/9251555/5125080/6d8bddbc-70c0-11e4-9277-68235bbe2399.PNG)

Båda länkarna fetmarkeras samtidigt.

**Comment by jeldeklint** [comment]
en tillfällig lösning här skulle vara att se till att två "föräldrar" i sid-akriv-trädet inte får sparas med samma url och byter ett barn url, får det typ propageras i trädet. Alternativt tillåta det sålänge bara en är publicerad.

**Comment by jeldeklint** [comment]
En fråga som
```SQL
select permalink, id, master_revision_id from page 
    where permalink in (
    select permalink from page 
        where master_revision_id is NULL group by permalink having count(*) > 1
    );
```
visar att det existerar dubbletter på t.ex. test. Fixar en varning på lagrummet för liknande.

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se

![skarmavbild 2015-01-21 kl 16 39 25](https://cloud.githubusercontent.com/assets/1655/5839086/26221d22-a18c-11e4-8dbd-95869dc6da4f.png)

**Comment by jeldeklint** [comment]
Hmm, det där ser lite funky ut.. borde bara vara ena felmeddelandet. tror jag vet varför. Ska nog ta bort en av dem..

Orsaken till att status sätts som publicerad där beror på hur den knappen fungerar - men den sparas inte trots att statusen sätts till publicerad.
Hur den funktionaliteten är går att diskutera. Men det är inget vi _måste_ åtgärda nu.

**Comment by lalindqv** [comment]
Kan inte skapa dublett - OK
