### ISSUE TITLE
Hur nå status "utkast - tidigare avpublicerad" ?

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#251]
Kan någon kontrollera i koden hur man kommer till sid-status  "utkast - tidigare avpublicerad" i publiceringflödet.
Jag har lyckats en gång tidigare genom att först avpublicera en sida och sedan spara som utkast  och fick alltså till:
"Publicerad" -> "Avpublicerad" -> "Utkast - Tidigare Avpublicerad"
Ikonen för "Utkast - Tidigare Avpublicerad" ser ut så här  ![icon utkast tidigare avpublicerad](https://cloud.githubusercontent.com/assets/9251555/5139438/94de76f6-715e-11e4-9ef4-9f2e893e9bcf.jpg)

**Comment by jeldeklint** [comment]
De status:ar på sidor som förkommer i koden är `draft` ("utkast"), `published` ("publicerad") och `autoSave` (osäker på hur det uppstår, möjligt att det är ett utkast som inte är sparat, förekommer i databaserna dock)
Allt annat är presentation som räknas ut vid rendering genom att kombinera sid-status med datum och status och datum på sidans eventuella "barn" (versioner som tillhör en huvud-sida)

**Comment by lalindqv** [comment]
Stänger detta ärende eftersom ikonen/statusen inte används.
