### ISSUE TITLE
Kan inte använda knappen "HTML" i Internet Explorer 11

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#263]
Knappen HTML är viktigt då man redigerar sidan "Vanliga Frågor".
Den fungerar inte i Internet Explorer 11.
Den fungerar i IE 10 och Firefox 33.

![bug html1](https://cloud.githubusercontent.com/assets/9251555/5180895/5701021e-7491-11e4-88dc-0183dfe26f9e.PNG)

Då jag klickar på "HTML" i IE 11 blir HTML SOurce Editor tom:
![bug html2](https://cloud.githubusercontent.com/assets/9251555/5180903/6948a7f6-7491-11e4-8158-56705c2f3057.PNG)

**Comment by jeldeklint** [comment]
Verkar fungera i.o.m uppdateringen av TinyMCE

**Comment by kamidev** [comment]
Fixad för IE 11 i och med uppdateringen. Notera att HTML-knappen ser lite annorlunda ut nu. Se bild nedan (HTML visas om man trycker på "< >" i nedre högra hörnet):

![skarmavbild 2015-01-12 kl 11 23 18](https://cloud.githubusercontent.com/assets/1655/5701591/babf261e-9a4d-11e4-8dae-dd1ee4b76eb3.png)

**Comment by lalindqv** [comment]
Finkar fint i IE 11
