### ISSUE TITLE
Det går inte att välja om publiceringsdatum ska visas eller ej

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#264]
Krav 79:  I varje sidmall finns inför publicering möjlighet att välja om datum för publicering ska vara synligt även på webbplatsen. 

Fel 1: Det går inte att som administratör välja om publiceringsdatum ska visas eller ej
Fel 2: Det framgår inte någonstans på lagrummet när sidan är publicerad, bara när den är senast granskad.

![bug gransk1](https://cloud.githubusercontent.com/assets/9251555/5183420/375e0d30-74af-11e4-9357-ad0c5da55ddb.PNG)

Det är fullt möjligt att ändra det senast granskad -datum som visas, vilket inte är samma sak som datum för publicering.

**Comment by helelun** [comment]
Bedömningen är att det är tillräckligt att visa ett datum, vilket vi gör idag. Ärendet kan stängas.
