### ISSUE TITLE
Förenkla installation av internreleaser och installation hos leverantör via Fabric

### ISSUE THREAD

**Issue by cheijken** [rinfo/lagrummet.se#270]
Vi behöver ha installationsstöd för en miljö som mer liknar drift. Det försvårar felsökning och driftsättning negativt att inte ha bra stöd för det.
Förslag är att byta ut hämtningen av Tomcat och installera standard som följer med debian. Väger fördelen med att ha en specifik version, mot att ha en av driftleverantören säkerhetspatchad version. Lösningen möjligen är att regelbundet kunna testa mot en så lik drift miljö som möjligt.

**Comment by karejonssondov** [comment]
Grundfrågan är obesvarad: Vad kräver en driftsmiljö?
Glesys har gett oss ett svar, DV-nätfolket ger oss troligen ett annat. I det här ärendet borde vi välja vad vi vill ändra. Om provskott finns en gren i Git som heter "packageinstall" för både lagrummet och rdl.

**Comment by karejonssondov** [comment]
För DV-nätet skulle installation via Puppet vara att föredra. Det gör också att vi inte är känsliga för skillnaden Red Hat och Debian.

**Comment by kamidev** [comment]
Ersätter detta ärende med ett nytt som bättre speglar nuläget: https://github.com/rinfo/lagrummet.se/issues/441
