### ISSUE TITLE
Visa söksträng vid miss.

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#278]
Om ingen träff vid sökning visas ingen information om vad man egentligen sökte på.
![soek](https://cloud.githubusercontent.com/assets/9251555/5224515/02037b1a-76d6-11e4-807e-9f636be314d5.PNG)

Om däremot träff visas söksträngen:
![soek2](https://cloud.githubusercontent.com/assets/9251555/5224531/3a3122bc-76d6-11e4-9590-ab1d1490e2f4.PNG)

**Comment by cheijken** [comment]
Fixed. Finns på gren ''feature/278_show_query_no_hits''
Testa genom att söka på en kategori och ett sökord som inte finns.

**Comment by lalindqv** [comment]
Hur testa ? Funkar inte på test.lagrummet.se

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se med full sökning påslagen.

**Comment by evajerr** [comment]
OK. Sökte på ett antal ord som inte gav träff. Sökordet upprepades i svaret på sökningan.
