### ISSUE TITLE
"Visa Fler Träffar" visar inte fler träffar

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#285]
Söker på "budget" och får två träff.
I resultatlistan visas korrekt "2 av 2" samt de två länkarna.
Men där visas också texten "visav fler träffar"
![bug budget1](https://cloud.githubusercontent.com/assets/9251555/5248230/ba95f0b8-7979-11e4-9cdb-99779789d92e.PNG)

Klick på "Visa fler träffar" ger

![bug budget2](https://cloud.githubusercontent.com/assets/9251555/5248234/c119236a-7979-11e4-9f75-f9be1650544b.PNG)

det enda som händer tycks vara att länken "visa fler träffar försvinner"

**Comment by cheijken** [comment]
Fixad. Finns på grenen ''feature/285_show_more_hits''.
Testa genom att söka på olika ord "a   ", hund, katt och rätt. Ger olika mängder sökresultat. Texten/Länken  "Visa fler träffar" skall döljas i de fallen sökresultaten understiger 5 träffar.

**Comment by kamidev** [comment]
Testade med sökning mot alla rättskällor påslagen. "Räksmörgåsar" ger en (1) träff.  "lantmäteri" hittar tre (3) lagar. I ingendera fallet visas längre "Visa fler träffar.

**Comment by evajerr** [comment]
OK. Sökte på "kameraövervakning privat sfär" som ger ett resultat av två träffar. Ingen text Visa fler träffar syns.
