### ISSUE TITLE
Kontakta oss-formuläret fungerar inte

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#287]
Om man skickar in ett formulär "kontakta oss"
![bug kontakta oss formular 0](https://cloud.githubusercontent.com/assets/9251555/5259164/67809030-79fc-11e4-8b9e-ce47af8b5a20.PNG)

Så får man ett 500 - fel

![bug kontakta oss formular 1](https://cloud.githubusercontent.com/assets/9251555/5259168/775772e4-79fc-11e4-91d9-3063a300759d.PNG)

**Comment by jeldeklint** [comment]
Det är ett känt fel p.g.a att `smtp`-server osv. inte är konfigurerad i lagrummet.
Ett annat fel är dock att fältvalideringen är trasig, detta p.g.a att jquerys `.html()` används för att läsa värdet av en `textarea`. `.html()` är mest en wrapper runt browserns egen `innerHTML()` vilken fungerar olika på olika browsers.
I IE fungerar det t.ex. p.g.a av att den skickar uppdaterade värden på fälten efter att DOM:en renderats, vilket inte Gecko baserade browsers gör.

Ändrar i stället till det lämpligare `.val()` (som används på annat ställe i samma sammanhang)

**Comment by jeldeklint** [comment]
Den verifiering av fält i kontakt formuläret som används i dag, dvs html5:s `required` har inte helt stöd i alla browsers (ofullständigt men fungerar i nyare Safari och stöds inte alls i iOS Safari, Opera mini och fick stöd i Android Browsern först i 4.4.4), valideringen blockerar således iPhones och många Android telefoner.
Vi borde kanske lägga in någon form av workaround eller byta validering sätt.
En grej som _borde_ göras är att även validera på serversidan. Vilket faktiskt inte görs idag. Inte OK. Även om det hemskaste här är att det kanske går att skicka tomma mail till lagrummet.

**Comment by jeldeklint** [comment]
Viktigt när `smtp`-konfigurationen fixas är att det inte checkas in ev. inloggningsuppgifter.

**Comment by cheijken** [comment]
Har efterforskat/testat SMTP och infört wiki http://wiki.lagrummet.se/index.php/Mail.
Lite osäker på hur denna skiljer sig från #124.

**Comment by cheijken** [comment]
Denna bugg borde vara klar:

**Comment by kamidev** [comment]
Komplettera gärna med beskrivning av hur man enklast testar.

**Comment by cheijken** [comment]
Instruktioner för att konfigurera lagrummets mail finns här
http://wiki.lagrummet.se/index.php/Mail
Utmaningen är snarast att hitta en SMTP server att testa mot.
Jag har testat med intern DV mail, men då måste man sitta på det nätet.
Möjligen skulle vi kunna konfigurera jenkins så att det går att skicka mail från den via localhost?
