### ISSUE TITLE
Länk för Avpublicering av Utkast visas.

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#291]
Länken visas tills man har klickat på den en gång.
Då man klickar på "Avpublicera" tycks inget annat hända än att länken "Avpublicera" försvinner. 

Förväntat: Länk till avpublicering ska aldrig visas för utkast eller för någon av de avpublicerade sidorna.
Förväntat: Endast den publicerade sidan ska kunna avpubliceras.

![bug avpublicera3](https://cloud.githubusercontent.com/assets/9251555/5261314/a40a228e-7a18-11e4-856d-ac5cf44db1f8.png)

**Comment by jeldeklint** [comment]
Knappen för avpublicering visas när en sida är i status `utkast` och är "huvud-version". Vore enkelt att åtgärda det.
En annan grej här att det skapas ett nytt utkast varje gång man klickar på `Avpublicera`..

"autoSaves" är förövrigt det halvtaskiga namnet i modellen på listan av versioner av sidan som är kopplade till den som visas när man öppnar en sida ("master-revision").

Sen finns det dessutom en status "autoSave" vilken jag inte är helt säker på hur man åstakommer, har sett den förekomma i databasen dock

**Comment by jeldeklint** [comment]
Jag håller på att trolla bort avpublicera för utkast som är huvud-version. Dock..
I dag finns inget stöd för att radera en huvud-version av en sida. Frågan är ska jag plocka bort "Ta bort"-knappen också, och ersätta den med en text som helt enkelt säger, "Gällande version, kan ej raderas".
_Eller_ implementera borttagning för gällande version? dvs Återställa föregående version och sedan utföra borttag på utkastet som gäller.. @lalindqv @helelun

**Comment by jeldeklint** [comment]
Eller rättare sagt tills #245 är inne, så går det utmärkt att radera huvud-versionen av utkast, vilket får tillföljd att den raderar **ALLA** andra versioner av den sidan också - publicerade eller ej.. @lalindqv @helelun

**Comment by lalindqv** [comment]
1. Behåll "Ta bort" - om och endast om den tar bort utkastet. ( det är ju utkastet som visas).
2. Ändra statustexten till "Utkast, publicerad version gäller" ( det står så i användardokumentationen - och vi ska inte införa en ytterligasre status eftersomm det skulle vara förvirrande)
Generellt bör ju alla operationer ske på det objekt man har uppe för tillfället.

**Comment by jeldeklint** [comment]
Eh, alltså tar man bort utkast som är huvudversion så försvinner allt. Ska jag ändra det beteendet så behövs endel grejer göras om.
Statusen "Utkast, publicerad version gäller" existerar bara som bild, finns inga textreferenser till den.
Logiken som väljer bild på sidträdet är tyvärr helt skild (och till stor del duplicerad) från det som hanterar en sidas status.
Namnet "Utkast, publicerad version gäller" är tyvärr helt bakvänt mot hur sidorna fungerar. En bättre text hade varit "Gällande utkast. Annan version publicerad."

**Comment by jeldeklint** [comment]
Döljt "Avpublicera" för alla utkast (visades tidigare bara för utkast som var huvud-version) och "Ta bort" för utkast som är huvud-version _och_ det finns andra versioner.

Vill man radera en sådan version får man återställa en annan version först och ta bort den andra sen.

**Comment by kamidev** [comment]
Verifierat på test.lagrummet.se att knappen "Avpublicera" ocjh "Ta bort" inte visas enligt ovan.

**Comment by lalindqv** [comment]
"Ta bort" tycks bara visas om utkastet inte varit publicerat - OK
"Avpublicera" visas inte för publicerad sida - OK

**Comment by jeldeklint** [comment]
nja, @lalindqv "Ta bort" visas bara för utkast som inte har några barn. Ett utkast kan aldrig ha _varit_ publicerat eftersom det skapas nya versioner hela tiden och när en version avpubliceras så ändras _inte_ status tillbaka till "utkast", utan det skapas en ny kopia i status "utkast" såvitt jag vet..
