### ISSUE TITLE
Ej valid html

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#299]
Kör man w3c:s validator på beta-lagrummet så visar den ett par fel. Det är osnyggt p.g.a att validerat.se kommer att köras på sajten, som andra myndighets sidor (http://www.validerat.se/sv/se-resultaten/statliga-myndigheter/l/lagrummetse/)

Felen beror på inkorrekt skriven html och vissa grails-features. Vissa IE10 buggar hade kunnat undvikas p.g.a detta. t.ex. #194 och #249 

ex:
http://validator.w3.org/check?uri=http://beta.lagrummet.se/webbkarta&charset=(detect+automatically)&doctype=Inline&group=0&user-agent=W3C_Validator/1.3+http://validator.w3.org/services

http://validator.w3.org/check?uri=http://beta.lagrummet.se&charset=(detect+automatically)&doctype=Inline&group=0&user-agent=W3C_Validator/1.3+http://validator.w3.org/services

**Comment by karejonssondov** [comment]
Här en utväxling med Tommy Bagler

1: Kåre -> Tommy

Har du kört http://validator.w3.org på den html VA spottar ur sig?

För blotta ögat var det inte lätt att se men för http://www.vagledandeavgoranden.dom.se/lagrummet/html/11968.html rapporterar den över hundra fel. Kan man byta till ett bättre verktyg för att generera html-koden?

2: Tommy -> Kåre

Vi kan inte byte verktyg utan att ändra på hela hanteringen. Allt bygger på wordfiler idag och att det är en slutanvändare som inte har någon specifik IT-kunskap som utför arbetet med att spara som html. Det är mycket möjligt att det finns andra verktyg än Word självt som kan göra den konverteringen på ett bättre sätt men det har jag ingen kunskap om
Då kanske man i stället titta på lösningsförslaget med att skapa PDF:er i stället för att frigöra sig från HTML i detta sammanhang. Oberoende av vilken väg man går kommer det att ta tid på grund av mängden dokument
