### ISSUE TITLE
Länkar till externa siter bör öppnas i ny flik eller fönster

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#302]
om man klickar på en länk som går utanför lagrummet.se, tex 
![bug extern](https://cloud.githubusercontent.com/assets/9251555/5296332/e000abc4-7ba2-11e4-82eb-f4b20b79ca6c.PNG)

så öppnas den i samma fönster 
![bug extern2](https://cloud.githubusercontent.com/assets/9251555/5296346/ff17b4d0-7ba2-11e4-9e6d-15eaf7850697.PNG)

Förslag1 : Meddela användaren om att man lämnar lagrummet.se
Förslag2 : Öppna den externa sidan i ny flik eller i ett nytt fönster.

**Comment by jeldeklint** [comment]
hmm, hur är det, finns krav på att saker som denna ska fungera med javascript avslaget? @lalindqv @helelun
För WCAG 2.0 tillåter väl iofs att man kräver javascript sålänge navigering m.m fungerar? Vill minnas att WCAG 1 inte tillåter det. Vad säger webbriktlinjerna egentligen?

**Comment by helelun** [comment]
Länkar till externa webbplatser ska enligt webbriktlinjerna (fortfarande) öppnas i samma fönster.
http://webbriktlinjer.se/r/5-skriv-tydliga-lankar/#lnkar-till-andra-webbplatser

Ingen åtgärd. Ärendet kan stängas.

**Comment by lalindqv** [comment]
Ja, det står ju faktiskt att länkar till externa webbplaster inte ska öppnas i nytt fönster.
