### ISSUE TITLE
"Visa Alla (N) Rättskällor" syns men gör inget när det är exakt 10 rättskällor

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#307]
![screenshot 2014-12-08 10 53 47](https://cloud.githubusercontent.com/assets/579622/5337466/280c956c-7ec9-11e4-8cf0-d1762cde9af5.png)
"Visa Alla 10 Rättskällor" syns här med gör inget. Beror på klassiskt "hur-många-element-i-arrayen"-fel.

**Comment by jeldeklint** [comment]
Det här är klart att testas,
För att testa, lägg till rättskällor under en rubrik (t.ex. "Regeringen") tills det finns t.ex. 11st. Verifiera att "Visa alla 11 ..." dyker upp.
Ta bort så det blir 10 och se att länken försvinner igen. (tips, i startdatan för att köra lokalt finns det 11-12 rättskällor)

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se

**Comment by evajerr** [comment]
Har testat med 10 resp 11 källor. När det är 11 källor visas de 10 första och det finns ett klickbart meddelande som kan visa resten.
Om det är gränsvärdet 10 källor visas de bara och inget med. Helt OK.
