### ISSUE TITLE
Tillåt ej tomma sökningar

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#311]
Just nu toppar tom sökning statistiken. Det känns otroligt onödigt att göra den sökningen samt att lägga in det i statistiken.

**Comment by cheijken** [comment]
Fixat.
Testa genom att köra in gren ''feature/311_prevent_empty_search'' i test och göra tomma sökningar.

**Comment by cheijken** [comment]
Fixat.

**Comment by lalindqv** [comment]
Sökning på tom sträng ger ett 500-fel:
Jag klickar alltså på Sök utan att ha skrivit något alls i sökfältet.
![tom](https://cloud.githubusercontent.com/assets/9251555/6783381/b5246f1c-d179-11e4-995d-aa8a09d15742.PNG)

**Comment by cheijken** [comment]
Inkört på *release/2.2*

**Comment by kamidev** [comment]
Finns för test på ville, valle och viktor.

**Comment by lalindqv** [comment]
OK - med tom söksträng. Vi kan stänga just detta ärende
#426 gäller fortfarande
