### ISSUE TITLE
Uppladdade filnamn ej unika

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#312]
Det görs ingen koll på om ett filnamn existerar redan eller ej, detta gör det möjligt att ladda upp filer som ej går att visa. Detta då lagrummet hämtar filer via filnamn, spelar ingen roll vilken sida eller puff som äger bilden/filen

**Comment by jeldeklint** [comment]
P.g.a hur puffar hanterar bilder idag går det ej att kasta in en "snabbfix" av det här ärendet.

**Comment by jeldeklint** [comment]
frågan är hur, om det här ska lösas, eller går det att leva med?
Vi skulle kunna kräva unika filnamn, fast då vore det praktiskt att tilllåta puffarna att koppla bilder från den globala bildbanken också. Finns det något krav som förklarar varför puffarna i dag bara går att koppla mot bilder som ägs av samma sida? @lalindqv @helelun

**Comment by lalindqv** [comment]
Jag tror att detta går at tleva med eftersom eventuella problem lätt upptäcks, dvs bilden syns inte.

**Comment by kamidev** [comment]
Kan vara att dokumentationen av admin kompletteras med en liten not om detta, d v s att filnamn bör vara unika.

**Comment by lalindqv** [comment]
Jon, du kan stänga detta ärende.

**Comment by evajerr** [comment]
Har norterat i Användarinstruktionen på sidan 10 att man ska göras uppmärksam på detta, att systemet inte kan hantera filer med samma namn.
