### ISSUE TITLE
Uppdatera TinyMCE

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#313]
Vi kör en drygt 3år gammal version av TinyMCE, vi kommer behöva uppdatera för eller senare p.g.a #263
lika bra att göra det så snart som möjligt.

**Comment by lalindqv** [comment]
Funkar utmärkt att använda nya versionen av TinyMCE för att bifoga dokument till en sida som en länk.
Se test.lagrummet.se, sida "Testar att bifoga dokument"

1. Ladda in dokument via Media->Ny bild eller fil
2. Tiny MCE: Insert/Edit link 
3. Ange URL som /+ filnam i Hantera media.

**Comment by lalindqv** [comment]
Fungerar utmärkt att lägga in länk till pdf-dokument som sparats via "Hantera Media".
Fungerar utmärkt att lägga in länk till jpeg-bild som sparats via "Hantera Media".

Bilden och dokumentet visas först när man klickat på länken - vilket är förväntat.

**Comment by jeldeklint** [comment]
det ska gå att välja bilder direkt från en dropdown (´Image list´) under `insert/edit image` också

**Comment by evajerr** [comment]
Har laddat in fil (bild) via Media.
La sedan upp den som en länk på en befinlig sida. Ändrade även ledtexten till länken. Förhandsgranskade och Publicerade. Fungerade utmärkt.

**Comment by helelun** [comment]
Texten i editorn breder ut sig åt höger utanför ramen. När jag fortsätter skriva blir texten osynlig men så småningom blir den synlig. Att texten inte håller sig inom rutan är ett fel som tycks ha återkommit?

Full screen och synlig html-kod jättebra!

Noterar att de olika rubrikstilarna ligger under Formats/Headings. Men jag saknar funktion för att välja brödtext. Till exempel för att ändra en rubrik till brödtext. Undrar också om jag kan lite på att text jag klistrar in från andra källor (worddokument, andra webbplatser) får rätt formattering när jag inte själv kan sätta brödtext-formatet.

Skapat en ny sida och skriver text i editorn. Fungerar bra förutom att texten breder ut sig utanför rutan - ett fel som har återkommit? Har klippt in texter både från lagrummet.se och andra källor.

**Comment by jeldeklint** [comment]
ska kika på det!

**Comment by jeldeklint** [comment]
så @kamidev @lalindqv @helelun 
ändrat "format" rullgardinen så att den innhåller samma val som innan uppdateringen. 
Bredden skall också vara åtgärdad.

**Comment by kamidev** [comment]
Installerade på test.lagrummet precis. Ser bra ut där.

**Comment by helelun** [comment]
Bekräftar att bredd och formatmeny ser bra ut i test.
