### ISSUE TITLE
Installera Syntax-highlighting plugin till TinyMCE

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#314]
För att underlätta redaktörers arbete borde vi installera en plugin till TinyMCE som ger syntax-highlighting  i html-läget.
Exempelvis, http://alexgorbatchev.com/SyntaxHighlighter/

**Comment by jeldeklint** [comment]
verkar fungera bra, för att testa, öppna code-funktionen (ser ut som `< >`) i TinyMCE, gärna på någon sida med mycket htmlkod typ "Vanliga frågor och svar". htmlkoden bör nu indenteras och färgläggas.

**Comment by lalindqv** [comment]
Wow ! 
Snygga färger, bra identering och radnumrering.
