### ISSUE TITLE
Se till att projektdokumentationen har en versionskontrollerad grafisk profil

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#320]
Se issue #310. Det finns redan en profil men allt är inte versionskontrollerat. Kanske räcker det att checka in CSS-filer? Vi bör inte göra oss beroende av manuella handgrepp.

**Comment by cheijken** [comment]
CSS:er ligger i RDL 
https://github.com/rinfo/rdl/tree/develop/documentation/styles
https://github.com/rinfo/rdl/commit/cd08e5b69cd15238c9cddb703b7e27e30953f188
Förstår inte riktigt hur ni tänkt?
