### ISSUE TITLE
Lägg in cookie-knapp med fastställt utseende och text 

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#321]
Standardfunktionalitet för att låta användaren veta och få möjlighet att godkänna användningen av cookies.

**Comment by jeldeklint** [comment]
Att inte sätta cookies innan användaren godkänt sätter stora pinna i analytics-hjulet. I vissa EU-länder, t.ex. Nederländerna är det OK att använda kakor utan användarens godkännande för webbanalys, så länge det är anonymt. Vilket är en bättre variant än det som PTS förespråkar, anser jag.

Jag hoppas lagen görs om snart, med tanke på hur många som skiter i det, alternativt sätter kakor innan man tryckt OK ändå.

Något som är rätt intressant är statistiken på hur många som lämnar sidor p.g.a dåligt designade kak-knappar. :disappointed:

Vi skulle kunna göra all analys på serversidan. Då skulle vi kunna klara oss helt utan kakor för vanliga användare. Men det är sämre och knöligt.
En intressant grej med kaklagen är att den ska vara teknikneutral så det spelar ingen roll om man sparar undan informationen i något annat än kakor..

**Comment by jeldeklint** [comment]
fun-fact.. domstol.se sätter kakor innan man tryckt på acceptera (det är mer regel än undantag..). dock säger PTS; "Du måste också se till att besökaren samtycker till att du använder kakor.". Frågan är ju vad samtycke är i det här fallet. Är att inte bry sig om "acceptera"-knappen ett samtycke?

**Comment by cheijken** [comment]
Fungerande förslag finns på grenen *feature/321_accept_cookie*

Bifogar lösningsförslag skärmdump
![screenshot lagrummet cookie use](https://cloud.githubusercontent.com/assets/2744439/5976929/65dee586-a893-11e4-9ba7-70ac4a1cd7b7.png)
![screenshot lagrummet cookie use2](https://cloud.githubusercontent.com/assets/2744439/5976933/6f85e864-a893-11e4-81f1-014e57e48eb0.png)

**Comment by kamidev** [comment]
Koden fungerar. Men har @helelun synpunkter på hur det ser ut/borde se ut?

**Comment by helelun** [comment]
Text:

Lagrummet.se använder kakor (cookies) för statistik och sökfunktion.
Om kakor och hur vi använder dem  (länkar till kakor-sidan på lagrummet.se)
Knapptext: Jag accepterar kakor

**Comment by helelun** [comment]
Utseende:

Neutral grå ruta med svart text.
Visa gärna något/några förslag innan vi sätter utseendet.

**Comment by cheijken** [comment]
Fixat enligt följade förslag. @helelun 
![nytt forslag for cookies](https://cloud.githubusercontent.com/assets/2744439/6149449/471ec574-b209-11e4-9cc4-9f3ddb4a73f8.png)

**Comment by cheijken** [comment]
Texten är fel. Återkom gärna med förbättringar. @helelun

**Comment by helelun** [comment]
Texten ligger i kommentaren ovanför kommentaren om utseende!

**Comment by helelun** [comment]
Lägg rutan ovanför det trefärgade strecket i stället. 
Hur skulle det bli om rutan endast ligger över sökfältesraden, alltså inte alls över vänsternavigeringen?

**Comment by cheijken** [comment]
![new cookie look banner above](https://cloud.githubusercontent.com/assets/2744439/6165466/77527552-b2a8-11e4-893c-57a87c847828.png)

**Comment by cheijken** [comment]
Finns det någon anledning till att animera cookie banner? @helelun @jeldeklint

**Comment by kamidev** [comment]
Ligger inne på develop nu och är funktionell. Men det finns ett layoutproblem som borde fixas. Kanske är det fixat och beror på något merge-problem? Se skärmdump nedan: 

![skarmavbild 2015-02-13 kl 16 08 36](https://cloud.githubusercontent.com/assets/1655/6189442/dc8ca4c2-b39a-11e4-884f-f3bbb7a84122.png)

**Comment by helelun** [comment]
Nej till animering!

**Comment by cheijken** [comment]
Kört in rättningen på *develop* grenen.

**Comment by cheijken** [comment]
Har även kommenterat bort en linje som syns ovanför sökresultatet som jag tyckte blev helt fel. Kaka på kaka. Jämför demo och beta.

**Comment by helelun** [comment]
Noterar att cookiefältet verkar poppa upp varje gång jag går in i demo. Även fast jag tidigare samma dag accepterat kakor. Och inte tömt webbhistoriken.

**Comment by helelun** [comment]
Felet att cookiefältet poppar upp varje gång jag går in i demo,  alltså efter det att jag först accepterat kakor,  kan jag idag inte återskapa. Omstart av webbläsare, F5 och Ctrl+F5 påverkar inte. Däremot återkommer cookiefältet efter omstart av datorn vilket inte borde ske?

**Comment by cheijken** [comment]
Hittade en liten detalj när jag testade med Firefox. Har rättat och det ser bättre ut i firefox. Den uppfattade cookien som en session cookie. Efter rättningen så är den korrekt långt fram i tiden.

**Comment by cheijken** [comment]
Nu borde denna vara fixad.

**Comment by helelun** [comment]
Demo beter sig nu enligt förväntan. Efter att ha accepterat cookies första gången jag går in i demo håller cookiefältet sig borta till nästa omstart av datorn. (DV tömmer numera historiken vid varje omstart).

**Comment by lalindqv** [comment]
OK - Funkar fint. Efter att ha acceptera cookies återkommer inte frågan.
