### ISSUE TITLE
Tar lång tid ( >30 sekunder)  att exportera sökhistorik

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#325]
Från det att man klickar på 
![export](https://cloud.githubusercontent.com/assets/9251555/5469259/c7331668-85d9-11e4-9e4d-9ddaef5cf01e.PNG)
tar det lite drygt 30 sekunder innan man får någon respons. Det är ca 10.000 rader som returneras vid testet.

Känns som att det är lång tid för så lite data och med bara en användare som lastar ner.  
Nu kanske det inte är något större problem att behöva vänta en minut eller två för att exxportera sökhistoriken, men kan detta vara et tecken på andra prestanda-problem ?

**Comment by jeldeklint** [comment]
skrev om exporten så att lokalt gick 10K rader från ~7.5s till ~600ms. Ingen skillnad mellan filerna. Databas-accessen är då 2/3 av den nya siffran.

**Comment by jeldeklint** [comment]
La till UTF-8 BOM också för att göra MS Excel glad. #330

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se

**Comment by lalindqv** [comment]
38.000 rader i Valle går så fort att exportera nu att det inte går att mäta ( med moraklocka iallafall).
