### ISSUE TITLE
Excellista lite svårläst

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#330]
Exporterar statisikdata till excel. Resultatet är lite svårt att tolka. Det hade varit lättare med kolumnrubriker. Hur ska "Ovrigt" tolkas?
Ser ut som att den inte klarar av att presentera läsbara tecken. 
Verkar vara å,ä och ö som inte fungerar.
![ri exceldump](https://cloud.githubusercontent.com/assets/9693918/5471195/f8064a08-85f2-11e4-9073-ceccc5e8f4d0.PNG)

**Comment by kamidev** [comment]
Verifierad mot test.lagrummet.se och IE10

**Comment by evajerr** [comment]
Nu klarar den Å,Ä och Ö. Det var förväntad justering. Fö gick det väldigt snabbt att få över informationen till excel.
