### ISSUE TITLE
Admin innehåller delar som inte finns i lagrummet

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#331]
Under inställningar kan man i admin välja "Kategorier i utfallande menyn". 
Det verkar inte som att "Utfallande menyn" finns kvar.
Bra om admin och lagrummet är synkroniserade. 

![ri utfallande menyn](https://cloud.githubusercontent.com/assets/9693918/5471323/70157a68-85f4-11e4-8ea1-532a996c6dc1.PNG)

**Comment by kamidev** [comment]
Instämmer med @jeldeklint om rutiner för hur redaktionellt arbete ska plockas in. Vi hade inte det inför helgerna nu och då blev det inte riktigt rätt. Och instämmer med @lalindqv: vi bör givetvis, rent generellt, försöka hålla synk på vad som går att göra via Admin inför releaser.
