### ISSUE TITLE
Senast granskad uppdateras oavsett om "Uppdatera granskad-datum" är satt eller inte

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#333]
Detta kanske är ett fel. Om jag gör en Ny sida utan att bocka i "Uppdatera granskad-datum" och väljer att Förhandsgranska denna så är Senast granskad satt (till dagens datum).
Om datumet uppdateras automatiskt så känns det egendomligt att kunna "bocka" i och välja "Uppdatera granskad-datum".
![ri granskad-datum ny sida](https://cloud.githubusercontent.com/assets/9693918/5485837/51edbc6a-86a0-11e4-9a64-c8a8bd02efc7.PNG)
![ri granskad-datum forhandsgranska](https://cloud.githubusercontent.com/assets/9693918/5485844/6427d640-86a0-11e4-86e2-8422a3444a64.PNG)

**Comment by kamidev** [comment]
Håller med @jeldeklint om att vi behöver prata ihop oss om hur det ska fungera. @lalindqv har nog rätt i att detta är ett fel och inte en förbättring. Men det är också en fråga om ambitionsnivå.

**Comment by kamidev** [comment]
Ingen åtgärd. För ny sida ska datum sättas på det här sättet.
