### ISSUE TITLE
Ser sida i trädstrukturen som endast finns som utkast

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#334]
Har skapat en ny sida och sparat den som Utkast. Har också petat in det på rätt ställe i trädstrukturen.

Eftersom det är ett utkast hade jag förväntat med att varken se sidan i trärstrukturen eller se sidan på lagrummet.se.
Sidan syns i trädstrukturen men inte om jag klickar på den. Ska det vara så?
![ri utkast admin](https://cloud.githubusercontent.com/assets/9693918/5486021/42384ee6-86a2-11e4-844f-6a6a0d15cd56.PNG)
![ri utkast lagrummet](https://cloud.githubusercontent.com/assets/9693918/5486027/5601803c-86a2-11e4-8065-9d1aa25bcbec.PNG)
![ri utkast sida finns ej lagrummet](https://cloud.githubusercontent.com/assets/9693918/5486054/a753e614-86a2-11e4-92e7-24c52f86141b.PNG)

**Comment by kamidev** [comment]
Löses genom att skapa särskild mapp via befintlig funktionalitet.

**Comment by jeldeklint** [comment]
Mjä, det är en workaround, ingen lösning. Finns en fix på den buggen som ställer till med det här i  #245 (6d9f027)

**Comment by evajerr** [comment]
Har försökt att upprepa felet geom att skapa en sida som spars som ett utkast och placera den på passande plats i menyträdet. Den syns inte på "lagrummet". 
Ändrar lite på utkastet och väljer sedan den "tvetydiga" Spara. Sidan behåller sin status = Utkast och inte heller då syns den i trädet på "lagrummet". Den syns först när jag väljer Publicera och det är som det ska vara.
