### ISSUE TITLE
Se till att klassen "searchLink" ligger på rätt länkar

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#339]
Framförallt vid dynamisksök behöver länkarna på resultatsidan ha klassen `searchLink` för att sökdata ska gå iväg till Analytics

**Comment by jeldeklint** [comment]
Kanske ska tillägga att det är till största del en regression av #220

**Comment by cheijken** [comment]
Fixad. Testa genom att installera feature på test. Kontrollera så att inställningarna aktiverar RDL i sökresultatet.
Gör en sökning på exempelvis "hund" och tryck INTE enter eller sök.
Kontrollera att länkarna i sökresultatet har klassen "searchLink". Antingen via visa källa eller inspekt element.

**Comment by kamidev** [comment]
Fungerar på develop, installerat på test och på demo.

**Comment by lalindqv** [comment]
Hittar ej SearchLink i HTML-koden. Christian har varit med och testat.
