### ISSUE TITLE
Rutin för att upptäcka brutna länkar

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#340]
Det ska finnas en rutin inom förvaltningen av lagrummet för att upptäcka brutna länkar. 
( detta är krav nr 12 från kravdokumentet)

**Comment by karejonssondov** [comment]
Linkchecker är ett trevligt gratisprogram Lars visat mig. Det finns mening med att köra det när databasen ändrats samt förstås när en ny version av systemet driftssatts. Det senare vet jag själv när det görs. Det förra är ett samspel mellan @helelun och mig.

**Comment by lalindqv** [comment]
Testa att ta bort en bild som är publicerad på en sida och sedan köra LinkCheckern...

**Comment by lalindqv** [comment]
Kan ej testa på Valle eftersom LinkChecker lyder robots.txt till punkt och pricka.

**Comment by lalindqv** [comment]
Funkar  fint. Tog bort en bild och ett dokument. LinkCheckern klagar precis som den ska.
![capture](https://cloud.githubusercontent.com/assets/9251555/5935608/e2fc50a2-a6dc-11e4-879d-e307bb78a0c8.PNG)
