### ISSUE TITLE
Kunna lägga dokument till redaktionella sidor

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#341]
Krav 57: Som redaktör vill jag kunna lägga dokument till redaktionella sidor.
Beslut: Om det går at spara dokument via ”hantera media” eller om det går att skapa area för filer och om det går att länka via html i textfönstret , så är det tillräckligt.

Gör så här:
1) Ladda in ikon för den typ av dokument som ska representeras. Behöver förstås bara göras en gång per dokumenttyp. Använd "Media" -> "Ny bild eller fil".

2) Ladda in själva dokumentet som ska länkas in vida "Media" -> "Ny bild eller fil".

3) Redigera HTML, tex:

![html](https://cloud.githubusercontent.com/assets/9251555/5523082/118e8e7a-89c4-11e4-83df-aff09154aefe.PNG)

Detta exempel ger en sida med en klickbar ikon.: 
![pdf1](https://cloud.githubusercontent.com/assets/9251555/5523000/abb433b2-89c2-11e4-8d1f-250cd9c9c51c.PNG)

Helene att testa.

**Comment by jeldeklint** [comment]
Vill vi borde det gå rätt enkelt att få till en filväjare i TinyMCE precis som att det går att infoga bilder. Men det känns inte prioriterat nu direkt.

**Comment by kamidev** [comment]
Borde vara fixat i och med #313 Uppdatera TinyMCE

**Comment by jeldeklint** [comment]
Nja, inte med. Använda länkar går i gamla TinyMCE också.

**Comment by kamidev** [comment]
Tolkningen av kraven - vid avstämmingen idag - var att det räcker att kunna länka. Stänger det här så länge.

**Comment by lalindqv** [comment]
Testa enligt instruktionen i #313

**Comment by lalindqv** [comment]
Funkar fint enligt #313. - OK

**Comment by evajerr** [comment]
Har laddat in ett word- och ett pdf-dokument.
När jag publicerat sidan med dessa filer som länkar så var de litë olika.
Pdf-dokumentet öppnades och visades direkt.
Worddokumentet kräver att jag väljer Öppna Spara eller Spara som
