### ISSUE TITLE
Lägg in text om tryckt version på framsökt dokumentsida

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#342]
Att implementera:
Krav 87: Som användare (vem som helst) vill jag på varje dokumentsida se en text om att det är den tryckta versionen som gäller.

Acceptanskriterier:
1) Valfri text (t.ex. att den tryckta versionen gäller eller att datakvaliteten kan variera mot den tryckta versionen/originalet) placeras under annan information i mittenkolumnen.
2) Texten ska kunna vara olika för olika typer av rättskällor. Till att börja med en (1) text för RK och ingen text alls för alla andra rättskällor.

**Comment by kamidev** [comment]
Skapar en ny issue för att ta fram den text som behövs.

**Comment by jeldeklint** [comment]
Exempel på hur RK implementerar detta:
http://rkrattsbaser.gov.se/cgi-bin/thw?%24%7BHTML%7D=sfst_lst&%24%7BOOHTML%7D=sfst_dok&%24%7BSNHTML%7D=sfst_err&%24%7BBASE%7D=SFST&%24%7BTRIPSHOW%7D=format%3DTHW&BET=1999%3A175%24

**Comment by kamidev** [comment]
Se ärende #347 för vilken text som ska läggas in.

Text om tryckt version är aktuellt för konsoliderade versioner av författningar. Till att börja med gäller det alltså SFS. Eventuellt blir det senare också aktuellt för myndigheters föreskrifter.

VA berörs alltså inte.

**Comment by cheijken** [comment]
Fixad. Finns i gren *feature/342_printed_version_text*
Testa genom att söka fram och visa en SFS. Nya texten skall då synas.

**Comment by helelun** [comment]
Fel text ligger ute. Se #347. 
Gör den uppdaterade texten kursiv i stället för fet.

Test & demo visar i IE10 texten även för grundförfattning, exempel:
![friskrivningstext pa grundff](https://cloud.githubusercontent.com/assets/6142669/6038013/b38a8b22-ac59-11e4-84f9-ddf057447c98.png)
Fler exempel: Lag (2006:1116) om information till passagerare m.m.

**Comment by cheijken** [comment]
Fixat på feature *feature/342_printed_version_text*.
Bifigar en skärmdump på nya utseendet och text.
![lagrummet issue 342 new look](https://cloud.githubusercontent.com/assets/2744439/6075945/a5f95ae0-addc-11e4-9e1e-0e098d63b391.png)

**Comment by helelun** [comment]
Felet att texten visas även för dokumentsida med grundförfattning kvarstår i test / IE10.

**Comment by lalindqv** [comment]
Ser ok ut:
![tryckt](https://cloud.githubusercontent.com/assets/9251555/6803951/367835be-d23b-11e4-8652-b3dc4f2a095f.PNG)

**Comment by helelun** [comment]
Visas som förväntat vid konsoliderade versioner av SFS.
Visas som förväntat inte alls vid grund- och ändringsförfattningar.
Visas korrekt för grundförfattning där ändringsförfattning saknas och där vi visar den som konsoliderad.
Kan stängas.
