### ISSUE TITLE
Funktion för att dölja avpublicerade sidor

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#344]
Att implementera
Krav 121:
Det ska finnas en funktion för redaktör för att dölja sidor som är avpblicerade.

**Comment by lalindqv** [comment]
Besrkiv workaround

**Comment by lalindqv** [comment]
Fungera mycket väl. Skapa en ny kategori, döp den ill något bra, se till att den inte visas i webbkarta och spara den som utkast.

Flytta sedan avpublicerade sidor till den nya kategorin.

KOm ihåg att avmarkera visa i webbkarta först.

**Comment by jeldeklint** [comment]
Webbkartan ska inte visa saker som inte är publicerade iom #229

**Comment by lalindqv** [comment]
Stänger denna.  Kan testas åter i 2.1 testerna.

**Comment by evajerr** [comment]
Det finns flera sätt att göra detta. Jag valde att skapa en sida som jag döpte till Papperskorgen. Bockade i Kategori och bockade ur Visa i webbkrata. Sparade och Publicerade.
Per automatik hamnar alla nya sidor ovanför Startsida och därmed är de osynliga oavsett status (Visa i Wekkkarta slår dock igenom).
Flyttade sedan godtycklig Avpublicerad sida till Papperkorgen. Fungerade bra.
