### ISSUE TITLE
Loginsidorna är tillgängliga

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#345]
Det går alldeles utmärkt att försöka logga in på:
.../login/full
eller
.../login/auth

version ( v2.0)

**Comment by kamidev** [comment]
Vilka maskiner och vilken version gäller detta?

**Comment by cheijken** [comment]
Klar.

**Comment by karejonssondov** [comment]
Restriktionerna är utlagda på produktion. @cheijken hade hittat konfigurationen och verifiering var det gott nog att införas i morse. Tyvärr inte utan problem men nu är det rätt. #351

För att stänga, använd en dator som inte når internet via DVs när och kolla att det blir blanka sidor på www.lagrummet.se/admin och www.lagrummet.se/login och www.lagrummet.se/login/full . Verifiera sedan att samma länkar ger innehåll om man går från DVs nät.

**Comment by kamidev** [comment]
Verifierat enligt ovan.

**Comment by lalindqv** [comment]
Testat på www ( ver 2.0 alltså).. Fungerar.

**Comment by evajerr** [comment]
Har testat både hemma och på DV nätverk 
www.lagrummet.se www.lagrummet.se/login www.lagrummet.se/login/full
Fungerar enligt förväntan med untantag av www.lagrummet.se/login på DV "Sidan kan inte hittas"

**Comment by jeldeklint** [comment]
Att sidan inte kan hittas för url:en `/login` är för att det inte finns något `route` för `/login` utan specificerad `action`. Lagrummet försöker då istället hämta en redaktionell sida med adressen `login`. Ska inte vara något nytt.

**Comment by kamidev** [comment]
Inloggning sker normalt genom att försöka gå till /admin (vilket automatiskt leder vidare till /login/auth). Att det inte går att komma åt /login är förväntat beteende.

**Comment by jeldeklint** [comment]
Mja typ, vart `/admin` leder beror på om man har en "remember me" kaka m.m. men i det stora hela, ja, gå dit så får man logga in.
Förövrigt går det komma åt `/login` bara man lägger upp en sida med den url:en - dock är `/login` ej nåbar i produktion från annat än DV:s nät p.g.a att det är _olika_ reguljära uttryck som blockerar vissa sökvägar och som väljer vilken sida man ska till. utt som väljer vilken bara hanterar `/login/(action)` detta är snarare en bugg då det finns kod för att visa inloggning även på `/login` den går bara svår att nå.

Exempel, hade fungerat inom dv.
![screenshot 2015-01-28 13 16 47](https://cloud.githubusercontent.com/assets/579622/5937451/ffc313c0-a6ef-11e4-86c8-f751e7f52614.png)

**Comment by kamidev** [comment]
Ingen showstopper nu. Förväntat beteende är att gå till /admin, vilket bör dokumenteras.
