### ISSUE TITLE
Skapa text om tryckt version 

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#347]
Krav 87: Som användare (vem som helst) vill jag på varje dokumentsida se en text om att det är den tryckta versionen som gäller.

I första hand behöver vi en text som fungerar för material från RK. 

 Issue #342 som implementerar ett sätt att lägga in denna text

**Comment by helelun** [comment]
Följande text gäller för dokumentsidor som presenterar konsoliderade versioner av SFS.

"Texten kan innehålla fel. En del bilagor saknas. Kontrollera vid behov mot den tryckta versionen av lagen/förordningen."

**Comment by kamidev** [comment]
@helelun: skulle detta med smärre modifikationer även kunna täcka VA?

**Comment by helelun** [comment]
Text om tryckt version är aktuellt för konsoliderade versioner av författningar. Till att börja med gäller det alltså SFS. Eventuellt blir det senare också aktuellt för myndigheters föreskrifter.

VA berörs alltså inte.

**Comment by kamidev** [comment]
Då tackar jag för texten och stänger det här ärendet.

**Comment by kamidev** [comment]
Texten inlagd enligt ovan.
