### ISSUE TITLE
Fel när bild kopplad till puff tas bort

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#352]
Bryter ut denna ur #323.
Handlar om att bildens `id` förekommer som nyckel när den är kopplad till en puff. Borttaget fungerar därför inte, vilket kanske inte är fel - men felmeddelandet gör att sajten 404:ar. mer info varför i #323.

**Comment by jeldeklint** [comment]
Ändrade så att man kommer tillbaka till bilden man försöker tabort och ändrade felmeddelandet så att det säger att om bilden är kopplad till en puff, behöver kopplingen tas bort först.

**Comment by kamidev** [comment]
Verifierad på test och demo

**Comment by lalindqv** [comment]
hohoo

**Comment by lalindqv** [comment]
Går inte ta bort media-fil om kopplingen används.
Går att ta bort koppling till mediafil om kopplingen inte "används"
Går att ta bort själva media-filen om den saknar koppling till sida elller puff.
