### ISSUE TITLE
Inledande bokstav faller bort på temporära startsidan i IE9 (med flera browsers?)

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#353]
En person har anmält att inledande bokstaven faller bort i texten på temporära sidan. Personen arbetar i IE9.

![inledande bokstav faller bort](https://cloud.githubusercontent.com/assets/6142669/5776070/e781a3ba-9d82-11e4-9fcc-ff6ce0555b94.png)

**Comment by jeldeklint** [comment]
har att göra med typsnittet `fira-sans`
https://code.google.com/p/googlefontdirectory/issues/detail?id=313
vill man se hur det ser ut i andra browser går det att använda t.ex. http://www.browserstack.com/screenshots

**Comment by jeldeklint** [comment]
ie 8 och 7 använder redan special-stil så de är inget problem.

**Comment by jeldeklint** [comment]
en redaktionell temporärfix vore att lägga in
```HTML
<!--[if IE 9]>
<style>
#content > article > p {
font: 12px verdana, arial, helvetica, sans-serif;
}
</style>
<![endif]-->
```
överst via html-editorn för första sidan. Det byter helt enkelt typsnitt för IE9

**Comment by kamidev** [comment]
Kolla statistik för användning av lagrummet. Vilka webbläsare ska vi prioritera?

**Comment by kamidev** [comment]
Det är viktigt både med användning "i allmänhet" och vilka myndigheter (t ex Domstolsverket) som vi kanske ska ta särskild hänsyn till.

**Comment by helelun** [comment]
Temporära kodfixen inlagd i skarpa lagrummet.se. Kan du testa i IE9 @lalindqv?

**Comment by lalindqv** [comment]
Fungerar inte på Win7 - IE9
Jag testar på 25 andra kombinationer och återkommer senare med resultatet.
Men så här ser IE 9 ut: 
![capture win7-ie 2015-02-27](https://cloud.githubusercontent.com/assets/9251555/6409544/74385f4e-be65-11e4-8140-0b14ea27657f.PNG)

**Comment by jeldeklint** [comment]
jao, jag vet redan varför, har smugit sig in ett mellanslag på felställe i "conditional comment":en. ska ta reda på varför.

**Comment by jeldeklint** [comment]
vi borde oavsett åtgärda detta _korrekt_ till nästa release.

**Comment by lalindqv** [comment]
Har nu testat:
Win 8.1 - IE 11, Firefox 31, Chrome 40,  Opera 12.16
Win 8 - IE 10, Firefox 31, Chrome 40
Win 7 - IE 8,9, 10, 11, Firefox 31, 20, Chrome 40, 30, Safari 5.1
Win XP - IE 7, Chrome 40, Opera 12.16, Safari 5.1
Mac OS X Yosemite - Opera 12.15, Safari 8
Mac OS X Mavericks - Chrome 36, Safari 7

Det är bara Win 7 - IE 9 som uppvisar problem.

**Comment by jeldeklint** [comment]
ja, och det är förväntat. ska bli samma på vista också.

**Comment by jeldeklint** [comment]
det är förövrigt nya tinyMce som förstör fixen, http://www.tinymce.com/forum/viewtopic.php?id=33462
jag testade det med den gamla versionen..

**Comment by jeldeklint** [comment]
Att göra något i stil med
```javascript
<script type="text/javascript" language="javascript">// <![CDATA[
function isIE () {
  var myNav = navigator.userAgent.toLowerCase();
  return (myNav.indexOf('msie') != -1) ? parseInt(myNav.split('msie')[1]) : false;
}
if ( isIE() == 9){
      document.querySelector("article.frontpage.editorial").style.font = "12px verdana, arial, helvetica, sans-serif";
}
// ]]></script>
````
skulle kringgå problemet

**Comment by lalindqv** [comment]
Redaktionell temporärfix tror jag inte blir så bra i längden. Jag har bara kontrollerat förstasidan och problemet kan ju finnas på andra sidor.

**Comment by jeldeklint** [comment]
ja, temporärfixar är typiskt obra i längden.
njä, felet kan inte riktigt finnas på andra sidor. typsnittet `fira sans` används _bara_ på den temporära startsidan.
Men hursom helst bör vi fixa det till nästa release som jag även skrev i fredags. finns en länk till en fungerade version av typsnittet i kommentar 2 https://github.com/rinfo/lagrummet.se/issues/353#issuecomment-70250431

**Comment by lalindqv** [comment]
Ok, tack då behöver vi inte testa den saken mer.
Måste säga att jag är lite imponerad av Browserstack. Mycket behändigt verktyg.

Med vänlig hälsning
Lars Lindqvist
Konsult, Testledare, Enheten för kommunikationskanaler, Domstolsverket
072-501 76 91 • lars.lindqvist@dom.se • Postadress: 551 81 Jönköping • Besöksadress: Kyrkogatan 34 • Fax: 036-16 57 21 • www.domstol.se<http://www.domstol.se/>


Från: Jon Eldeklint [mailto:notifications@github.com]
Skickat: den 2 mars 2015 08:56
Till: rinfo/lagrummet.se
Kopia: Lindqvist Lars - DOV
Ämne: Re: [lagrummet.se] Inledande bokstav faller bort på temporära startsidan i IE9 (med flera browsers?) (#353)


ja, temporärfixar är typiskt obra i längden.
njä, felet kan inte riktigt finnas på andra sidor. typsnittet fira sans används bara på den temporära startsidan.
Men hursom helst bör vi fixa det till nästa release som jag även skrev i fredags. finns en länk till en fungerade version av typsnittet i kommentar 2 #353 (comment)<https://github.com/rinfo/lagrummet.se/issues/353#issuecomment-70250431>

**Comment by cheijken** [comment]
Stänger.
Vält testat. Innan. Har verifierat med browserstack. Test ok.

**Comment by lalindqv** [comment]
Fungerar på viktor.lagrummet.se
Är inte implementerat på www.lagrummet.se
