### ISSUE TITLE
Ledtexter tas ej bort automatiskt

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#354]

**Comment by kamidev** [comment]
Se issue #261

**Comment by jeldeklint** [comment]
Jag kommer att byta till html5 placeholders istället för det konstiga hemma-hacket som är där nu. Redaktörer får se till att ha en någorlunda modern webbläsare.

**Comment by kamidev** [comment]
Låter vettigt.

**Comment by jeldeklint** [comment]
har åtgärdat ledtexten på rubriken för sidor i admin nu.. passade på att göra lite saker runt omkring också. ska se så det här inte smäller något flödestest bara.

**Comment by kamidev** [comment]
Verifierad på test.lagrummet.se och demo.lagrummet.se.

**Comment by helelun** [comment]
Jag får ingen ledtext alls när jag skriver rubriken. Jag kan inte skriva något i editor-fältet då det inte går att klicka in markören. 
Fixen fungerar alltså inte för redaktörers webbläsare IE10.
Testat i demo och test.

**Comment by jeldeklint** [comment]
har du tömt sidans cache?

**Comment by jeldeklint** [comment]
lustigt, IE10 har stöd för den funktionen som används. hmm. gräver lite i det.

**Comment by jeldeklint** [comment]
okej, den finns där, men den försvinner när fältet får `focus` i IE 10. Vi sätter `focus` automatiskt. därför syns den inte.
Tror det går att lösa smidigt med "infield-labels" för mer konsistent beteende.

**Comment by jeldeklint** [comment]
en intressant sak är att standarden säger att ledtexten ska synas tills fältet får `focus`. inte tills man börjar skriva..
Hur som, tror jag har en fix. Ska undersöka hur den beter sig i IE10. Den innefattar snarare att inte sätta `focus` automatiskt.

**Comment by jeldeklint** [comment]
Så, har testat en fix i IE10 ser ut att fungera ok.

**Comment by kamidev** [comment]
Verifierat med IE10 mot test.lagrummet.se.

**Comment by helelun** [comment]
Fungerar nu i IE10 på test.lagrummet.se.
