### ISSUE TITLE
Ta bort fält "Menystyling" ?

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#356]
Fältet "Menystyling" verkar inte inte användas för någonting alls.
Kan det tas bort ?

![capture2](https://cloud.githubusercontent.com/assets/9251555/5815778/2eef4ec8-a099-11e4-8e22-3d82f604ecb9.PNG)

**Comment by helelun** [comment]
Menystyling styr ordningen på rubrikerna i vänstermenyn (Rättsinformation, Hit vänder du dig, Lär dig mer). Kan alltså inte tas bort.

**Comment by jeldeklint** [comment]
Det styr inte direkt ordningen _men_, det styr utseende på sagda meny, med hjälp av css-klasserna `huvudmeny1`, `huvudmeny2`, `huvudmeny3` förekommer ett par andra exempel i databasen också. Således precis som @helelun säger, kan ej tas bort (nu).

Det skulle gå att automatiskt välja stil på menyn istället. men det känns oprioriterat. kanske något för lagrummet 3.0..

**Comment by jeldeklint** [comment]
Skulle nog snarare se att den här stängs. Eftersom premissen för ärendet är falsk. Finns ingen orsak att bygga om sådana grejer. Och spara det här till den dagen lagrummet mer eller mindre byggs om från scratch känns onödigt.

**Comment by kamidev** [comment]
Håller med @jeldeklint. Stänger ärendet.
