### ISSUE TITLE
Ta fram statistik för att prioritera webbläsar-specifika buggar

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#357]
Tittar någon på DV på generell webbläsaranvändning? Finns det någon färdig prioritering?

**Comment by kamidev** [comment]
@helelun: kan du ta en tit på hur det ser ut för gamla lagrummet?

**Comment by kamidev** [comment]
Målet är att få ett underlag för att prioritera om vi t ex ska fixa buggar som bara finns i IE9 eller andra mindre vanliga webbläsare. Se #353

**Comment by jeldeklint** [comment]
statistik plockas lämpligtvis från analytics (det fungerar på nuvarande lagrummet också)

**Comment by kamidev** [comment]
Kolla gärna lite extra på hur www.domstol.se har hanterat olika webbläsare.

**Comment by jeldeklint** [comment]
domstol.se verkar fingerprinta på user-agent och ser ut att lägga till css:er beroende på browser på serversidan. Även om flera av de css-filerna sedan är tomma..
Inget jag helst gör av olika orsaker.

**Comment by helelun** [comment]
Dokument i sharepoint visar användning av olika browserversioner under perioden 141208-150208.
Noterar utifrån resultatet att IE9 är relativt vanlig.
