### ISSUE TITLE
Diskutera testmiljöer för browsertest

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#358]
DV behöver se över hur testmiljöer för browsertest ska sättas upp. Det kan tex ske genom att virtuella maskiner förvaltas eller genom att använda färdiga tjänster för liten peng: tex http://www.browserstack.com (klarar att reproducera det inrapporterade felet i IE 9) , http://www.spoon.net eller http://www.modern.ie ( verkar kunna tankas ner och installeras lokalt)

Notera att nägra av dessa tjänster erbjuder parallell testning av olika browsers och versioner därav.

**Comment by kamidev** [comment]
Hänger ihop med #357

**Comment by kamidev** [comment]
Hur gör IT? Finns det redan planer?

**Comment by karejonssondov** [comment]
Lars visade ett par av tjänsterna som nämns ovan. Att rutinmässigt använda dem för att verifiera nya sidor hos oss eller nya webläsare/versioner är rimligt. För att mekanisera detta tycks saknas i dagsläget en idé om hur och vad som skall kollas men å andra sidan är det svårt att föreställa sig hur man väljer det.

**Comment by karejonssondov** [comment]
browserstack har visat god funktionalitet.

**Comment by kamidev** [comment]
Stänger detta ärende efter diskussion med @karejonssondov. Detta är en framtida drift och förvaltningsfråga.

**Comment by lalindqv** [comment]
Ok. Då skrivet jag det i den teststrategi jag ska lämna efter mig.


lars lindqvist | konsult | sogeti ab
mobil 072 501 76 91


-------- Originalmeddelande --------
Från: Kami Development AB <notifications@github.com>
Datum:10-02-2015 16:08 (GMT+01:00)
Till: "rinfo/lagrummet.se" <lagrummet.se@noreply.github.com>
Kopia: "Lindqvist, Lars" <Lars.Lindqvist@sogeti.se>
Rubrik: Re: [lagrummet.se] Diskutera testmiljöer för browsertest (#358)


Stänger detta ärende efter diskussion med @karejonssondov<https://github.com/karejonssondov>. Detta är en framtida drift och förvaltningsfråga.
