### ISSUE TITLE
Se till att lagrummets design klarar att visa ändringsposter som ändrar flera olika författningar 

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#360]
Hur ser det egentligen ut när vi visar en ändring som påverkar flera andra poster? Och förmodligen då även har flera titlar, kanske olika prop:ar(?) o.s.v. Borde de listas fallande på något sätt? @helelun 

Jag har inget exempel på utseende just nu eftersom mycket av datan har gått förlorad förut, p.g.a att filer skrevs över i RK:s export. Så idag syns bara det senaste inlästa.
För konsoliderade dokument är det meningen att #157 och rinfo/rdl#146 ska lösa problemet

**Comment by jeldeklint** [comment]
Samma sak med Vägledande avgöranden, se t.ex. http://beta.lagrummet.se/rinfo/publ/rf/ra/2001:67.
Inte helt snyggt. Fältet "titel" verkar inte visas korrekt för hänvisande mål i högerspalten heller..

**Comment by jeldeklint** [comment]
Orsaken till att "Titel" ser tom ut i exemplet ovan (RÅ 2001:67) är att det finns två hänvisningar - vilket sidan inte klarar..

**Comment by cheijken** [comment]
Fixat enligt nedan i *feature/360_fix_array_presentation*
Jag tror att jag väljer rätt fält att visa, men kanske en jurist skulle dubbelkolla detta?

Problem:
![lagrummet issue 360 problem](https://cloud.githubusercontent.com/assets/2744439/6058208/8b8a7340-ad25-11e4-842f-67aa8aaffc00.png)
Lösning:
![lagrummet issue 360 sollution](https://cloud.githubusercontent.com/assets/2744439/6058211/96f82c2c-ad25-11e4-942f-5232474a2cc4.png)

**Comment by cheijken** [comment]
Fixat även framtida möjlighet för multipla titlar. Visar beteckningen högst och titlarna som h3 under varandra. Även justerat titel på några andra ställen, samt ytterligare information som skickas med i form av konsoliderar och issued in.
För att testa kan det vara bra att kontrollera SFS 2007:636 och även byta källa till skrapat, där finns de multipla titlarna som när RDL är fixat kommer att finnas med i det skarpa SFS:erna.

**Comment by jeldeklint** [comment]
schysst! jag tror inte att "införs i" används i datan vi får från RK nu, i skapat finns den dock.

**Comment by cheijken** [comment]
Jupp när införs i kommer med i RDL så kommer det *magiskt* att fungera i lagrummet. :smile: 
Sökte igenom koden en gång till och gjorde några fixar där jag kontrollerar om det finns multipla titlar och byter ut dem till identifieraren i stället.
Tror denna uppgift är klar.

**Comment by kamidev** [comment]
Uppgiften är väl klar när #157 och rinfo/rdl#146 är klara? Och de är det ju inte än.

**Comment by cheijken** [comment]
Om denna inte är klar. Vad åsterstår?

**Comment by jeldeklint** [comment]
den borde vara ~done se rinfo/rdl#146
ska skriva testinstruktioner, det är inte helt trivialt.

**Comment by kamidev** [comment]
Incheckad på develop och verifierad på test. Se skärmbilld:

![skarmavbild 2015-03-03 kl 15 18 26](https://cloud.githubusercontent.com/assets/1655/6464174/af8e13ee-c1b8-11e4-9505-d298df940e34.png)

**Comment by lalindqv** [comment]
Jag tycker det ser tydligt och informativt ut i högerkolumnen under Hänvisande Rättsfall.

**Comment by lalindqv** [comment]
Kan inte hitta något fel i RÅ 2001:67:
![200167](https://cloud.githubusercontent.com/assets/9251555/6663549/0917c90a-cbc8-11e4-9711-95ebe4fbb47e.PNG)

**Comment by lalindqv** [comment]
SFS 2007:636 ser ju konstig ut, men titeln är ju som den är:
Däremot tycker jag att det ser helt
![2007636](https://cloud.githubusercontent.com/assets/9251555/6663640/f2be1d2a-cbc8-11e4-9c79-91dcd17aea3b.PNG)
 OK ut i högerspalten med alla författningar som ändras.

**Comment by helelun** [comment]
Instämmer i Lars bedömning ovan om titel och högerkolumn.
Jag gick vidare i högerkolumnen bland Grundförfattningar som ändras och tog upp dokumentsidan för Marknadsföringslag (1994:450). Noterar att ändringsförfattning (2007:636) presenteras i högerkolumnen utan ikraft-datum. Samtliga lagändringar i 2007:636 träder ikraft 1 november 2008. Jag vet att ikraft-datum saknas ibland, men är orsaken här specifik för denna SFS som ändrar flera andra SFS?

![andringsaknardatum](https://cloud.githubusercontent.com/assets/6142669/6664312/d4868a9e-cbce-11e4-9179-7c6d155b7c99.png)
