### ISSUE TITLE
Liten skilnad i publicera Från/Till

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#361]
Jag upptäckte en mycket liten skillad i publicerings datum mellan version 2.0 och 2.1.5:

Version 2.1.5
Publicera Från: Datum, månad och timme måste ha ett värde
Publicera Till: Datum, månad och timme kan vara "" 

Version 2.0
Publicera Fårn och Till: Datum, månad och timme kan vara "" 

Vet inte om detta indikerar något problem, men skillnaden finns där.

**Comment by jeldeklint** [comment]
jag tog bort möjligheten att ha ett tomt värde på "från" i #250 eftersom systemet inte kan hantera det under huven.

**Comment by lalindqv** [comment]
Då tycker jag att vi stänger denna utan åtgärd. Det var bara skillnaden jag vill påpeka.
