### ISSUE TITLE
Ändra logik kring sättande av titel för dokument i kategorin "Rättspraxis"

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#363]
_From @kamidev on January 27, 2015 15:28_

_From @kamidev on May 5, 2014 12:17_

Dokument i kategorin "Rättspraxis" ska använda underliggande data för beteckning som titel. 

Eventuellt ska alltför långa textsträngar klippas vid ett visst antal tecken i användargränssnittet.

_Copied from original issue: rinfo/lagrummet.se#130_

_Copied from original issue: rinfo/rdl#157_

**Comment by kamidev** [comment]
_From @jeldeklint on June 4, 2014 14:3_

hade vi några felaktiga exempel här? @helelun ?

**Comment by kamidev** [comment]
_From @helelun on August 26, 2014 11:42_

Det normala är (ska vara) att ett dokuments text-titel presenteras som titel. 

Undantaget är (ska vara) rättspraxis där vi på titelraden ska visa beteckning i stället för text-titel. 
(Exempel på beteckning: NJA 1997 s. 717, RÅ 1994 ref. 21).
 
I ett mindre antal rättsfall saknas beteckning. Då ska vi i stället visa målnummer. 
(Exempel på målnummer: 5587-1, Ö4646-96, T328-81).

Om det i en träfflista finns poster där både beteckning och målnummer visas ska poster med beteckning prioriteras högre. Nu verkar det vara tvärtom. 

Exempel i betan:
Jag fritextsöker på ordet "skuld" med avgränsning till vägledande domar. De tre första sidorna ger träffar med målnummer som titel. Från sid fyra får jag posterna med beteckning som titel. Första träff är 5587-1 som, när jag öppnar posten, visar sig leda till referatet RÅ 1994 ref. 21. Själva referatet presenteras först i mitten av sid 4.
Om jag preciserar min sökning till "skuld utdömt skadestånd" blir målnummer 5587-1 första träff, och själva referatet 2:a träff. Även här är det referatet som är intressant och bör visas först.

**Comment by kamidev** [comment]
_From @helelun on August 26, 2014 11:47_

Jag måste gå tillbaka till kraven. Det finns ingen anledning att visa poster med målnummer när motsvarande post finns som referat och därmed har fått sin beteckning. Vi lyfte upp målnummer för de domar där referaten ännu inte har skrivits, och beteckning alltså saknas. 

Uppdatering: eventuella undantag för poster med målnummer hantereras senare. Se issue #182.

**Comment by kamidev** [comment]
_From @jeldeklint on September 9, 2014 13:51_

Angående sorteringsordningen så beror den på hur relevansen av olika fält förstärks i sökmotorn, den är identifierare (beteckning) * 100 och titel * 20. Målnummer har ingen förstärkning alls.

Referatet "RÅ 1994 ref. 21" saknar titel, och referatrubriken saknar också förstärkning därför kommer den efter domen som ser ut att ha referatets referatrubrik som titel.

Förstärkningen av fält behöver göras om, frågan är bara hur vi gör det smidigt för en administratör, se rinfo/rdl#132

**Comment by kamidev** [comment]
Flyttar även denna till RDL

**Comment by jeldeklint** [comment]
Varför inte bara öppna #130 igen?

**Comment by kamidev** [comment]
@jeldeklint: jag gör så.
