### ISSUE TITLE
Webbkartan visar alla publicerade versioner av samma sida.

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#364]
Har man två versioner publicerade av en "sida" _samtidigt_ så kommer webbkartan att visa dem som syskon.
![screenshot 2015-01-28 12 55 20](https://cloud.githubusercontent.com/assets/579622/5937217/19e2ab7e-a6ed-11e4-98c5-b818cbe55181.png)

**Comment by jeldeklint** [comment]
Har knopat ihop en fix, inte helt nöjd, var tvungen att ta bort den tidigare datum sorteringen för att lagrummet ska visa _samma_ sida som webbkartan.

**Comment by kamidev** [comment]
Kan inte längre återskapa problemet. Stänger.

**Comment by jeldeklint** [comment]
För att testa detta, få två versioner av en sida publicerade samtidigt genom att använda "återställ" på en tidigare version.

**Comment by evajerr** [comment]
OK. Har tagit en befintlig sida (som finns i webb-kartan) och valt en tidigare version av samma sida och Återställt den.
Om jag gjort rätt så fungerar detta och sidan förekommer bara en gång i webb-kartan.
