### ISSUE TITLE
Gruppering av sökresultat

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#365]
Sökresultat vid sökning på alla källor tycks grupperas enligt i följande:
- Information från lagrummet.se
- Propositioner och skrivelser
- Rättsfall
- Lagar och förordningar
- Myndigheters föreskrifter
- Utredningar

Stämmer det ?

**Comment by helelun** [comment]
Ovanstående är de kategorier som idag gäller för den kategoriserade träfflistan. I betasök kommer vi att kunna visa dokument i tre av dessa kategorier (information från lagrummet.se, Rättsfall, Lagar och förordningar). Övriga kategorier bör, om de ska synas, ha kompletterande text "Dessa dokument är inte sökbara i denna version av lagrummet.se." (se beta).

**Comment by lalindqv** [comment]
Tack.

**Comment by kamidev** [comment]
Ska vi överväga att bara visa de tre vi har? Det gör sökresultatet tydligare och enklare. @helelun, @lalindqv?

**Comment by lalindqv** [comment]
Ja, jag tycker att det är fel att i varje träfflista informera om vad man INTE kan söka. Den informationen borde framgå på annat sätt.

Man kan undra på vilket sätt de olika kategorierna är ordnade. Rättsfall borde visas före Propositioner och skrivelser. 

Överhuvudtaget bör det not framgå tydligare vad som är sökbart och inte sökbart, speciellt när myndigheterna börjar droppa in.

![capture](https://cloud.githubusercontent.com/assets/9251555/6000771/64ad980a-aae2-11e4-964c-40aefe99776b.PNG)

**Comment by jeldeklint** [comment]
Just nu är de sorterade på den ordning de kommer i vyns markup, finns dvs inga programmatiska regler.  Hur ordningen valdes kanske @helelun vet.

Hur det annars ska framgå när det är en fritextsök är tycker jag är svårt att säga, i den utökade söken är det tydligare. 
Som det är kodat nu visas dessutom texten att det inte är sökbart på propositioner även om man får träffar, t.ex. i skrapat.

**Comment by helelun** [comment]
Vi visar endast de källor som är sökbara i kategoriseringsvyn.

Vilka rättskällor som är sökbara/inte sökbara framgår av sidan Alla rättskällor.

Längst ned på kategoriseringsvyn finns Sökhjälp - där finns också länk till alla rättskällor.

**Comment by jeldeklint** [comment]
@helelun ser ut som i koden att kategorierna som syns nu alltid syns oavsett val i kategoriseringsvyn.

**Comment by helelun** [comment]
Möjligen pratar vi om olika saker.
Kategoriseringsvyn = kategoriserade träfflistan. Kan inte påverkas av redaktör/admin.
Avgränsningsmenyn = droplisten för avgränsad sökning i anslutning till fritextsökfältet. Admin styr vad som ska visas i avgränsningsmenyn. Admin kan välja att begränsa alternativen till färre kategorier än vad som faktiskt finns i kategoriseringsvyn.

I betasök håller jag alltså med om att vi i kategoriseringsvyn endast visar de kategorier som finns.

**Comment by jeldeklint** [comment]
Då är jag med! Ja, så ser det ut, kategorierna "Information från lagrummet.se", "Propositioner och skrivelser", "Rättsfall", "Myndigheters föreskrifter" och "Utredningar" är hårdkodade i det som i såfall heter Kategoriseringsvyn. De visas alltid oavsett om det finns data eller ej.

**Comment by helelun** [comment]
"Myndigheters föreskrifter" ligger kvar i kategoriseringsvyn i Viktor. Ska döljas liksom vi har dolt "Utredningar" m.m.

![doljmyndfskr](https://cloud.githubusercontent.com/assets/6142669/6736365/a6148ee8-ce64-11e4-85b3-daed7986bbad.png)

**Comment by kamidev** [comment]
Verifierad på test och demo.

**Comment by lalindqv** [comment]
OK
