### ISSUE TITLE
Felmeddelande om kopplingen till RDL går ned ?

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#373]
Bäste vore: Ett korrekt meddelande till användaren om att kopplingen till RDL är bruten och att sökning bara kanske i lagrummet.se. 
I andra hand: ett tekniskt felmeddelande typ SERVER ERROR.
Det vore inte bra om användaren får typ "0 dokument funna..." som sökresultat, dvs ingen information om att kopplingen faktiskt gått ner.

Ta bort kopplingen till RDL på någon maskin så att vi kan testa.

**Comment by kamidev** [comment]
Testade genom att konfigurera om RDL på test.lagrummet.se till en annan maskin. Allt fortsatte att fungera. 

![skarmavbild 2015-02-10 kl 15 32 50](https://cloud.githubusercontent.com/assets/1655/6128892/1e9520dc-b13a-11e4-9060-2d26faff5a11.png)

Stängde sedan av den externa maskinen som levererade sökningen.

![skarmavbild 2015-02-10 kl 15 25 58](https://cloud.githubusercontent.com/assets/1655/6128773/2cca9e26-b139-11e4-94b7-0f3cf56ffa65.png)

**Comment by kamidev** [comment]
Notera också att sökningar mot redaktionellt material inte påverkas alls.

**Comment by kamidev** [comment]
Här behöver vi fånga den saknade uppkopplingen och ge användaren ett felmeddelande som tydligt visar att det inte går att genomföra sökningen.

**Comment by lalindqv** [comment]
Detta tycker jag är en klar bugg.
Sökningen mot RDL ska inte rapportera "0"-träffar när den uppenbarligen inte kan få någon träff alls.
Svaret kommer också väldigt snabbt ( < 1 sekund).

MInsta förväntade beteende är att sökningen väntar, timar ur, och sedan ger ett tekniskt fel typ "timeout error" när koppligen mot RDL är nere.

**Comment by cheijken** [comment]
Hittade en tidigare fel sektion i gränssnittet. Har aktiverat den. Några åsikter?

![lagrummet connection error message](https://cloud.githubusercontent.com/assets/2744439/6165869/94725af0-b2ab-11e4-8a81-f87d70c1cf1d.png)

**Comment by cheijken** [comment]
Kom gärna med tankar och åsikter kring utseendet på felmeddelandet samt texten? Några tankar.
@helelun @lalindqv @jeldeklint @kamidev

**Comment by lalindqv** [comment]
Jag tycker att det felmeddelandet i sig är tilräckligt bra.
Viktigare kansek är att om felet uppkommer bör någon också larmas för att felsöknig i loggarna ska kunna påbörjas så fort som  möjligt.

**Comment by cheijken** [comment]
Lösning. Visar ett tidigare dolt felmeddelande, samt tog bort dubbletter.
Lösningen på grenen *feature/373_rdl_connection_fail_message*.

**Comment by lalindqv** [comment]
Mycket bra.


lars lindqvist | konsult | sogeti ab
mobil 072 501 76 91


-------- Originalmeddelande --------
Från: Kami Development AB <notifications@github.com>
Datum:13-02-2015 15:28 (GMT+01:00)
Till: "rinfo/lagrummet.se" <lagrummet.se@noreply.github.com>
Kopia: "Lindqvist, Lars" <Lars.Lindqvist@sogeti.se>
Rubrik: Re: [lagrummet.se] Felmeddelande om kopplingen till RDL går ned ? (#373)


Closed #373<https://github.com/rinfo/lagrummet.se/issues/373>.

**Comment by helelun** [comment]
1. Jag tänker att vi bör informera användarna om hur de ska agera. Även om det är så enkelt som att prova igen om en liten stund.
"Något gick fel i sökningen. Det är inte säkert att sökresultatet är komplett. Prova igen om en liten stund."

2.  Ska ett felmeddelande gå i någon riktning (se Lars tidigare kommentar) om sökningen fortfarande inte fungerar efter en liten stund?
