### ISSUE TITLE
Anpassa startsidans layout efter betafunktionalitet för sökning

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#374]
Anpassningar inför release 2.2: 
- visa inte dropdown-meny för kategorival
- visa inte länk till "utvidgad sökning"
- visa inte dynamisk nerfallande meny när söksträngen skrivs in

**Comment by cheijken** [comment]
Så här ser sökningen ut enligt ditt önskemål. Kanske lite sisådär???
![testskott ny stripped search head](https://cloud.githubusercontent.com/assets/2744439/6147729/c50aca28-b1fa-11e4-8065-1a4210dd96b5.png)

**Comment by kamidev** [comment]
Synpunkter på formuleringen? @helelun?

**Comment by helelun** [comment]
Skriv så här så länge:

Sök bland lagar & förordningar, domstolars rättspraxis och ur texter på lagrummet.se
