### ISSUE TITLE
Fastställ utformningen av länk från www.lagrummet till beta.lagrummet.se

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#376]
Vi måste i god tid se till att vi vet:

- Hur ska länken från www till beta-versionen se ut och var ligger den på sidan?
- Vad skriver vi om betans syfte och innehåll?
- Var finns den beskrivande texten?

Vi behöver redaktionella ändringar från @helelun. Vad vill vi kommunicera? Men vi behöver också veta hur sidan ska ut.

**Comment by kamidev** [comment]
För att konfigurera olika startsidor från samma kodbas går det förhoppnings att återanvända befintlig funktionalitet. Men stäm av med @karejonssondov att han har allt han behöver för att kunna testa både www och beta på staging-servern.

**Comment by cheijken** [comment]
Bollat med @helelun. Blir en helt redaktionell ändring i en av puffarna med någon undersida. Vet inte hur jag skall ta detta ärendet vidare? @kamidev

**Comment by kamidev** [comment]
Då är det viktiga bara att se till at ändringen blir gjord på någon maskin ganska snart och att vi sparar den den inför deploy. @karejonssondov behöver en databasdump där ändringen finns med.

**Comment by cheijken** [comment]
Eftersom detta helt och hållet är en redaktionell ändring, behöver den inte ha samma version och driftsättning som övriga delar. Möjligen dagen (eller ett par dagar) efter. Kanske ärendet skulle ligga på Helene? @helelun @kamidev

**Comment by lalindqv** [comment]
Ärendet har tagg "Specification" - alltså kravspecas. Jag tycker att utformningen av en länk ingår i en kravspec.

**Comment by kamidev** [comment]
Det beror på vilken detaljnivå en kravspec ska vara. Här talar vi om layout och visuell utformning för en en specifik beta-release, inte grundläggande funktionalitet i själva applikationen.

**Comment by lalindqv** [comment]
Häpp. Nu blev det riktigt fel av mig. 
jag menar att det INTE ingår i en kravspec på systemnivå , såna krav skulle vara alldeles för detaljerade.

Står: Ärendet har tagg "Specification" - alltså kravspecas. Jag tycker att utformningen av en länk ingår i en kravspec.

Ska vara:
Ärendet har tagg "Specification" - alltså kravspecas. Jag tycker att utformningen av en länk INTE ingår i en kravspec.

**Comment by kamidev** [comment]
Vi har konsekvent använt "specification" när det krävs någon form av specifikation för att implementation ska kunna påbörjas/fortsätta. Det gör taggen till ett användbart planeringsverktyg. 

Den sorts specifikations som beskrivs i de ursprungliga systemkraven ligger för det mesta på en mindre detaljerad nivå.

**Comment by kamidev** [comment]
@helelun: nästa steg är att testa länkandet till vår beta-release. @karejonssondov förbereder en installation på stage.lagrummet.se som du kommer att kunna testa att länka till. Vi återkommer...
