### ISSUE TITLE
CasperJS - trunkering av söksträng

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#377]
Syfte med testet: Att konrollera funktion för trunkera inmatad söksträng finns och fungerar.
Se bug #286 

Test:
1. Ange en lång söksträng på lagrummet, tex 512 
2. Kontrollera att söksträngen trunkerats till 100 tecken.

Använd gärna en söksträng som visar antalet tecken ( i detta exempel visar siffran nästa teckens position i strängen):

A3A5A7A9A12A15A18A21A24A27A30A33A36A39A42A45A48A51A54A57A60A63A66A69A72A75A78A81A84A87A90A93A96A100A104A108A112A116A120A124A128A132A136A140A144A148A152A156A160A164A168A172A176A180A184A188A192A196A200A204A208A212A216A220A224A228A232A236A240A244A248A252A256A260A264A268A272A276A280A284A288A292A296A300A304A308A312A316A320A324A328A332A336A340A344A348A352A356A360A364A368A372A376A380A384A388A392A396A400A404A408A412A416A420A424A428A432A436A440A444A448A452A456A460A464A468A472A476A480A484A488A492A496A500A504A508A512A

**Comment by cheijken** [comment]
@kamidev hur skall denna prioriteras?

**Comment by cheijken** [comment]
Finns på *feature/377_text_max_query_truncate*

**Comment by lalindqv** [comment]
Alltför Lång söksträng ger problem. Se relaterad bugg.


lars lindqvist | konsult | sogeti ab
mobil 072 501 76 91


-------- Originalmeddelande --------
Från: cheijken <notifications@github.com>
Datum:12-02-2015 11:40 (GMT+01:00)
Till: "rinfo/lagrummet.se" <lagrummet.se@noreply.github.com>
Kopia: "Lindqvist, Lars" <Lars.Lindqvist@sogeti.se>
Rubrik: Re: [lagrummet.se] CasperJS - trunkering av söksträng (#377)


@kamidev<https://github.com/kamidev> hur skall denna prioriteras?
