### ISSUE TITLE
Ändra felaktiga fältrubriker på resultatsida

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#378]
![skarmklipp](https://cloud.githubusercontent.com/assets/9251555/6169111/7c4f1e70-b2cb-11e4-8fc8-7e188742020d.PNG)

**Comment by kamidev** [comment]
Problemet är inte kolonet. Utan att syftningen blivit fel på två ställen. 

Ändra "Författning som ändrar" till "Författning som ändras" och "Författning som upphäver" till "Författning som upphävs". Kolonet står kvar.

**Comment by cheijken** [comment]
Kört in på *develop*.

**Comment by kamidev** [comment]
Verifierat på demo.

**Comment by lalindqv** [comment]
Se ok ut. Kan nog stängas

**Comment by helelun** [comment]
Ok även för upphävande författning:

![ffupphavs](https://cloud.githubusercontent.com/assets/6142669/6825194/fb8f9f96-d2f8-11e4-914c-529bf33c0b30.png)
