### ISSUE TITLE
Visa inte träffkategorier som aldrig har träffar i sökresultatet

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#380]
Endast kategorierna "Information från lagrummet.se", "Lagar och förordningar" samt "Rättsfall" ska visas i träfflistan. 

Gör de andra kategorierna (som alltid har 0 träffar) osynliga, så att det går att slå på igen när vi får sökbara rättskällor för dem.

**Comment by cheijken** [comment]
Kört in på *develop*

**Comment by kamidev** [comment]
Kategorierna är borta. Notera att det fortfarande finns problem med vilka träffar som visas om det finns många träffar. Detta löser sig förhoppningsvis med https://github.com/rinfo/rdl/issues/154

**Comment by lalindqv** [comment]
OK
