### ISSUE TITLE
Ändringar i lagrummet för att få det att fungera med ny elasticsearch fråga

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#383]
Ändringar med t.ex. top resultat på den kategoriserade sidan
relaterar till t.ex. rinfo/rdl#152 och rinfo/rdl#154
skulle nog kunnat öppna #191 också.

**Comment by cheijken** [comment]
Redan mergad med develop. Testats i andra ärenden. Stänger denna.
