### ISSUE TITLE
Förslag på CaspeJS regressionstest - Sidfot

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#384]
Det ska finnas en sidfot på lagrummmet.se 
Vad sidfoten ska innehålla kan inte preciseras, mer än att om den innehåller länkar så ska länkarna fungera. Testet ska alltså inte utgå från att länkarna finns, utan ska bara försöka klicka på dem om de finns (självklart för en människa).

Selenium IDE -test ( python):
# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Sidfot(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "http://change-this-to-the-site-you-are-testing/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_sidfot(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        try: self.assertEqual("Om webbplatsen", driver.find_element_by_css_selector("li.heading").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        try: self.assertEqual("Om lagrummet.se", driver.find_element_by_xpath("//footer[@id='siteFooter']/ul[2]/li").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        try: self.assertEqual("Kontakta oss", driver.find_element_by_xpath("//footer[@id='siteFooter']/ul[3]/li").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text("Kakor (cookies)").click()
        try: self.assertRegexpMatches(driver.find_element_by_css_selector("h1").text, r"^Kakor[\s\S]*$")
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text(u"Teknisk information & användningstips").click()
        try: self.assertRegexpMatches(driver.find_element_by_css_selector("h1").text, r"^Teknisk information[\s\S]*$")
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text(u"Länkar du hittar på lagrummet.se").click()
        try: self.assertEqual(u"Länkar du hittar på lagrummet.se", driver.find_element_by_css_selector("h1").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text(u"Rättsinformation - rättskällorna").click()
        try: self.assertEqual(u"Rättsinformation - rättskällorna", driver.find_element_by_css_selector("h1").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text("Juridisk information").click()
        try: self.assertEqual("Juridisk information", driver.find_element_by_css_selector("h1").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text("Om lagrummet.se").click()
        try: self.assertEqual("Om lagrummet.se", driver.find_element_by_css_selector("h1").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text("Kontakta oss").click()
        try: self.assertEqual("Kontakta oss", driver.find_element_by_css_selector("h1").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text(u"Så svarar vi på e-post").click()
        try: self.assertRegexpMatches(driver.find_element_by_css_selector("h1").text, r"^Så svarar[\s\S]*$")
        except AssertionError as e: self.verificationErrors.append(str(e))
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()

**Comment by kamidev** [comment]
This issue was moved to rinfo/lagrummet_test#6
