### ISSUE TITLE
Förslag på CasperJS regressionstest - Toppmeny

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#385]
Det ska finnas en toppmeny på lagrummet.se. Toppemnyn innehåller normalt länkar till English, Webbkarta och Lyssna.  

Selenium IDE test ( python):

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Toppmeny(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "http://change-this-to-the-site-you-are-testing/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_toppmeny(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        try: self.assertTrue(self.is_element_present(By.LINK_TEXT, "Lyssna"))
        except AssertionError as e: self.verificationErrors.append(str(e))
        try: self.assertTrue(self.is_element_present(By.LINK_TEXT, "Webbkarta"))
        except AssertionError as e: self.verificationErrors.append(str(e))
        try: self.assertTrue(self.is_element_present(By.LINK_TEXT, "English"))
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text("English").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()

**Comment by kamidev** [comment]
This issue was moved to rinfo/lagrummet_test#7
