### ISSUE TITLE
Förslag på CasperJS regressionstest - Sökhjälp

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#387]
Det ska finnas en sökhjälp eller länk till sida med sökhjälp om användaren inte får träff.

Selenium IDE - test ( python):

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class SKhjLp(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "http://change-this-to-the-site-you-are-testing/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_s_khj_lp(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        driver.find_element_by_link_text("lagrummet.se").click()
        driver.find_element_by_id("query").click()
        # Sök på något som garanterat inte ger träff
        driver.find_element_by_id("query").clear()
        driver.find_element_by_id("query").send_keys(u"hfdsk#¤%&mklop")
        driver.find_element_by_id("searchSubmit").click()
        try: self.assertTrue(self.is_element_present(By.LINK_TEXT, u"Sökhjälp"))
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_link_text(u"Sökhjälp").click()
        try: self.assertRegexpMatches(driver.find_element_by_css_selector("h1").text, r"^Sökhjälp[\s\S]*$")
        except AssertionError as e: self.verificationErrors.append(str(e))
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()

**Comment by kamidev** [comment]
This issue was moved to rinfo/lagrummet_test#9
