### ISSUE TITLE
Räkneverket i listvyn döljs inte när alla träffar visas

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#389]
När jag klickar på "Visa alla xx träffar" i listvyn i viktor och demo listas som förväntat alla träffar men räkneverket längst ned är felaktigt kvar. (Så är det inte på beta).

![visa alla xx traffar](https://cloud.githubusercontent.com/assets/6142669/6345240/f4d87c7e-bc03-11e4-959c-e79ff03f16f0.png)

![rakneverket](https://cloud.githubusercontent.com/assets/6142669/6345256/37d4418e-bc04-11e4-9a74-93c83925f227.PNG)

**Comment by kamidev** [comment]
Fixen är incheckad och listvyn har förväntat beteende på demo.

**Comment by evajerr** [comment]
OK räkneverkat är borta när Visa alla xx är vald. 
Däremot är listan "ful" för vissa VA men det breor antagligen på att datat ha denna kvalitet. Det är massor av text bitvis och oöverskådligt.
