### ISSUE TITLE
Byt namn på kolumn i listvyn för Rättsfall

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#390]
"Beteckning" skall byta namn till "Referat/Dom" i listvyn för kategorin Rättsfall.

![skarmklipp](https://cloud.githubusercontent.com/assets/9251555/6346583/7b62d80e-bc11-11e4-8003-c676f30290d0.PNG)

**Comment by kamidev** [comment]
FIxen incheckad och har förväntat beteende på demo.

**Comment by lalindqv** [comment]
OK: Står referat/dom nu.
