### ISSUE TITLE
Lägg till fält/banner på varje sida i betasajten som anger att det är en betasajt

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#394]
På varje sida på betasajten ska det tydligt framgå att detta är en betasajt. Förslaget är att göra en banner motsvarande cookiefältet. Bannern ska hela tiden ligga kvar. Bannern kan ligga i överkant eller i nederkant. Bannern ska vara synlig även när man skrollar. Tilldelad utvecklare samråder med mig om lämplig text och utseende.

**Comment by cheijken** [comment]
Några första förslag att fundera på hur det kan se ut. Kom gärna med funderingar.
Detta är en mix av kraven att det är viktigt att det framgår tydligt att sökfunktion och söksvar på denna site är under utveckling och ej tillförlitliga, samt bibehållen användarupplevelse.
![screenshot from 2015-03-05 13 52 11](https://cloud.githubusercontent.com/assets/2744439/6551512/0272c868-c63a-11e4-9886-75835a44573e.png)
![screenshot from 2015-03-05 15 07 25](https://cloud.githubusercontent.com/assets/2744439/6551514/0a116d90-c63a-11e4-8f76-5a9d6f499390.png)
![screenshot from 2015-03-09 08 48 43](https://cloud.githubusercontent.com/assets/2744439/6551516/0fb1051c-c63a-11e4-89b1-26ace27c7d2f.png)

**Comment by cheijken** [comment]
Förslag 1: Banner högst upp som är synlig hela tiden.
![screenshot from 2015-03-05 13 52 11](https://cloud.githubusercontent.com/assets/2744439/6551531/32f34ecc-c63a-11e4-8f3b-8f11bdcad1ed.png)

**Comment by cheijken** [comment]
Förslag 2: BETA skrivet bredvid loggan, samt informationsruta vid söksvar.
![screenshot from 2015-03-05 15 07 25](https://cloud.githubusercontent.com/assets/2744439/6551538/545d3d48-c63a-11e4-8d5f-f2f0d2d7b570.png)

**Comment by cheijken** [comment]
Förslag 3: Variant på förslag 2, med lite ändrat BETA layout och bakgrund med BEAT utskrivet.
![screenshot from 2015-03-09 08 48 43](https://cloud.githubusercontent.com/assets/2744439/6551546/75212bc0-c63a-11e4-974f-4558ebab0eec.png)

**Comment by cheijken** [comment]
Ok uppfattar detta som valet. Med BETA banner högst upp och stillastående högst upp vid skroll.
@helelun uppdaterar texter.
![beta show](https://cloud.githubusercontent.com/assets/2744439/6619029/9b979796-c8c7-11e4-98b2-8699b4970699.png)

**Comment by helelun** [comment]
Skriv så här:
Beta! Du är nu i betaversionen av lagrummet.se. Här kan du direkt på sajten söka SFS och domstolars rättspraxis. Sökfunktionaliteten är under test och utveckling vilket innebär att fel förekommer.  

Länktext till skarpa sajten:	Gå till lagrummet.se

Den andra länken tas bort.

**Comment by cheijken** [comment]
Finns löst på feature. *feature/394_beta_banner*

**Comment by helelun** [comment]
Har kollat bannern i test. I stort sett bra! Betabannern ligger som förväntat över cookiebannern. Betabannern ligger kvar överst när jag skrollar.

Åtgärdas:
1. Förtydliga länken till skarpa sajten genom att ändra länktexten till "Gå tillbaka till lagrummet.se".
2. Uppdatera länken, den fungerar inte nu.
3. Skriv BETA! med versaler och lägg på röda färgen (enligt grafiska profilen).

**Comment by lalindqv** [comment]
Varför har detta ärende tagg "Specification" ?
Jag tycker inte vi ska ha en separat kravspec för betan.

**Comment by cheijken** [comment]
Uppdaterat enligt nya instruktioner. 
Kört in direkt på *develop* grenen.

**Comment by kamidev** [comment]
Verfierad på test

**Comment by lalindqv** [comment]
Bannern finns på alla sidor, utom sidan "English", vilket jag tycker är ok.
