### ISSUE TITLE
Underlag för att utföra prestandatest önskas

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#397]
Vi behöver prestandatesta lagrummet och sökningar mot RDL. Att man som ensam användare upplever att svarstiderna är tillräckligt bra räcker inte. Redan vid 2 ( eller 20 eller 200 eller 2000 "samtidiga användare" ) kan stora problem uppstå.

I #119 antyds att vi redan nu misstänker att vissa sökningar kommer att ta lång tid. Vilka typer av sökningar är det ? 

Vilken typ av resurs tror vi tar slut först  ( CPU, minne, nätverk etc) ? 
Hur monitorera resurserna ?

**Comment by jeldeklint** [comment]
i #119 verkar snarare handla om laddning av jobbig metadata (ej dokument!) från service, det är även denna som varnish kan cacha. slöa elasticsearch-sökningar pratades det inte om (iaf strax efter) när #119 skapades.
Elasticsearch-sökningar cachas dessutom inte av varnish, dock kan den cacha rätt friskt internt.
Kan tilläggas att jag och @cheijken råkade plåga ES-söken lite. det gick helt ok - antagligen för att den cachar internt. 
Så vi måste skicka olika/roterande/slumpade frågor till sökmotorn annars kommer den nog bara cacha upp sökningarna och vi har ett värdelöst test..

**Comment by lalindqv** [comment]
Tack.
Då vet jag att vi måste tänka på cachningen vid test.
Men är det någon speciell typ av sökningar vi bör testa.
Vad menar ni med "råkade plåga lite..."

**Comment by jeldeklint** [comment]
Vi testkörde `ab` lite snabbt mot elasticsearch för att se vad hände, den fick väl i.a.f `1000` samtidiga användare.

**Comment by lalindqv** [comment]
ab ???
Vad hände ? Svarstider ?

Vad tror du är tyngst ? 
Sök -> presentation av kategoriserade träfflistan ?
Klick på en dokumentlänk -> Presentation av dokumentet + länkar till alla refererande dokument ?
Sök i RDL vs Sök i lagrummet ?
Sökning på något vi vet genererar träff vs. Sökning på rappkalja tex "%&¤GSHGfgcsgahf" ?

Hur stort är cachet ? ( Hur många olika sökningar måste vi ha innan vi kan börja återanvända dem ?)

**Comment by jeldeklint** [comment]
inledande wildcard gissar jag är tyngst om vi tillåter det.

`ab` är [apache-benchmark](http://httpd.apache.org/docs/2.2/programs/ab.html), enkelt klassiskt `CLI` lasttestare
vi borde kunna tömma cachen med `curl -XPOST 'http://localhost:9200/rinfo/_cache/clear'` eller liknande. Finns ett par tips här: http://stackoverflow.com/questions/25212911/how-to-turn-off-caching-when-testing-elastic-search

Hur stort vårt cache är så antar jag att det är standard inställningar på, om jag miss rätt betyder det att den använder upp till `10%` av det `RAM` den har tillgängligt (vilket nog är i krokarna `512-1024MB`)
Annars är jag ingen stjärna på hur elastics cache beter sig.

Ang. resultatet av vårt ful-test. Det var i stil med "5-minuter-nu-ser-vi-vad-händer", inget spännande. sajten svalde det. men det var ju samma fråga hela tiden. Minns inte om det tog en liten stund för första requestet. Men det var inte speciellt vetenskapligt genomfört.

**Comment by jeldeklint** [comment]
Sen skulle jag säga att det är viktigt att skilja på de olika delarna av `rinfo`
laddning av meta-data från `sesame` via `rinfo-service` cachas t.ex. av `varnish`, hur det är med dokument som kommer via `rinfo-main` är jag osäker på.

Göra sökningar på knasiga grejer tror jag är dumt, då det inte skulle vara speciellt realistiskt - om man nu vill simulera belastning från användare.

tror det inte är speciellt stor skillnad på synonym eller ej.

Men _allt_ är ju intressant att testa :smile:

**Comment by lalindqv** [comment]
Att testa ALLT, det är mycket det.

Nej, jag tror inte synonym har någon betydelse heller.

Frågan om att söka på knasiga grejer , typ "¤%&S" eller felstavningar typ "Fstightslagen", är om det belastar systemet mer eller mindre jämfört med om vi får träff. 

Ja, vi bör testa med cachet avstängt. Åtminstone till att börja med. Det är lättare att se problem då, samt att om vi får rimliga svarstider utan cache så behöver vi inte testa så mycket mer. Finns ingen anledning att försöka sänka servern.

Med rinfo-main antar jag att du menar Atom-feeden in till RDL ? Innebör det också  att du menar att vi bör prestandatesta "inputt"-delen till RDL ? 

Ja, det är väldigt viktigt att kunna skilja på de olika delarna så att vi vet vad vi testar. Optimalt är om vi kan testa en del i taget. Sen kan vi simulera verkligheten, kanske genom att utnyttja befintlig sök-statistik.

**Comment by jeldeklint** [comment]
frågan är ju bara _hur_ realistiska - felstavningar är ju en grej men att 1000 pers sitter och söker på `¤%&S`.

Nej, jag syftar inte på `Atom`-feedsen i `rinfo-main`. 
`rinfo-main` levererar även _brödtexten/dokumenten_ till lagrummet och vid en "fler-nods-installation" finns det ingen `HTTP-accelerator` framför `rinfo-main` det är en potentiell flaskhals, men då är å andrasidan redan söken klar. 

Att använda sökhistoriken tror jag är bra.

**Comment by lalindqv** [comment]
Test av insamling från RDL:
. Inläsning från RK tar ca 5 timmar på en lite klenare testserver.
Eftersom RK är den i särklass största källan är det rimligt att anta att alla andra inläsningar tar kortare tid.
Det är ej heller kritiskt hur lång tid inläsningen tar. Nästa inläsning börjar inte förrän den pågående är klar. Vi har också krav från RK på att inte läsa oftare än en gång per dygn.

Test av sökfunktionen:
Prestandatest av sökfunktionen kan delas upp i själva sök-presentation av träfflista samt  att hämta dokument från RDL. 

Test av Sök:
Lasten vid prestandatestet simulerar verkligheten genom att sökstatistiken från beta.lagrummet och www.lagrummet.se används som söksträngar.
Prestandatestet gör i övrigt inga försöka att simulera en verklig användare som behöver tid för att knappa in söksträngen och läsa resultatet utan den virtuelle användaren kommer att söka så fort lasttestgeneratorn förmår generera sökningar. Ur resultatet kan man sedan härleda antalet sökningar per minut  och vilken svarstid respektive last ger. Detta kan sedan användas för att beräkna svarstiderna för ett verkligt antal besökare, givet att en verklig användarare behöver en viss bestäketid.

Prestandatestet kan ske mot stage.lagrummet.se, vilken är en ganska produktionslik server.
