### ISSUE TITLE
"Konsolideringsunderlag" skall ej presenteras på konsolideringar

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#399]

**Comment by jeldeklint** [comment]
ping @cheijken

**Comment by kamidev** [comment]
Fungerar på demo. Ändrade en regressionstest till det nya förväntade beteendet: att inte visa några konsolideringsunderlag.

**Comment by lalindqv** [comment]
Konsolideringsunderlag ska inte presenteras i högerspalten för dokument.
![399](https://cloud.githubusercontent.com/assets/9251555/6552562/55f377b4-c647-11e4-996d-7daf49c2901f.png)

**Comment by evajerr** [comment]
OK. Ser inga konsolideringsunderlag nu bara Ändringsförfattningar.
