### ISSUE TITLE
Irrelevanta träffar i Lagar och förordningar. Träff på sökord saknas

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#400]
Får inga gulmarkeringar och antagligen inga träffar
                                            Antal träffar = 9440 men det är mer troligt att 0 träffar stämmer

![fotoforbud](https://cloud.githubusercontent.com/assets/9251555/6551234/58fb2c16-c635-11e4-970e-ae0f2f8ce52e.PNG)

eller ännu tydligare , om man söker på något som inte borde finnas:
![sok pa vad som helst](https://cloud.githubusercontent.com/assets/9251555/6551245/73380220-c635-11e4-9bac-4f85be39eda0.PNG)

**Comment by kamidev** [comment]
Se även exempel med "Fotoförbud"

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#168

**Comment by lalindqv** [comment]
OK
