### ISSUE TITLE
Sökning på identifierare borde ge mer exakt träff

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#401]

**Comment by lalindqv** [comment]
Eva:
Jag hittar vad jag söker men även en massa onödiga träffar och jättemånga sådana eftersom sökningen plockar upp ”sfs” som ett sökbegepp.
                                            Sfs 1998:150 är en beteckning och jag undrar om inte systemet ska känna igen /förstå det?  
![401](https://cloud.githubusercontent.com/assets/9251555/6551328/0653c016-c637-11e4-8e3d-77207cd41d93.PNG)

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#166
