### ISSUE TITLE
Gulmarkera länk i träfflista

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#402]

**Comment by kamidev** [comment]
Se även underliggande implementation i https://github.com/rinfo/rdl/issues/153

**Comment by lalindqv** [comment]
Eva: Söker på en exakt referatsbeteckning. Träfflistan är relevant.
Det som är gulmarkerat är kanske lite ”ologiskt”.De två översta är referatet men träffen ser ut att vara MIG. Borde inte rubriken MIG 2014:20 markeras. Det är ju ändå den som gör att de kommer först? Om träffen MIG är det signifikanta så borde träfflistan omfatta ”alla” referat från migrationsdomstolen.

![402](https://cloud.githubusercontent.com/assets/9251555/6552532/084dc4ec-c647-11e4-9d9f-1661cbe57499.PNG)

Åtgärd: Gulmarkera länken om den innehåller träff(ar)

**Comment by cheijken** [comment]
Idag väljs det fält som visas är inte alltid **text**, utan i ordningen 'title','referatrubrik', 'text', 'identifier'. Detta påverkar om jag lägger till flera gulmarkeringar i andra fält, på vis att det kan exempelvis visas två titlar. Jag kommer att ändra så att *titel*, *text* & *identifierare* alltid visas och gulmarkera träffar i dem. Kollar vidare hur rättsfall påverkas av detta.
![best match order](https://cloud.githubusercontent.com/assets/2744439/6553030/90429d78-c64c-11e4-8e19-5fc4fe58207e.png)

**Comment by cheijken** [comment]
Så här kan nya träfflistor se ut med träffar titel, text och identifierare gulmarkerade.
![new yellow ish search hits](https://cloud.githubusercontent.com/assets/2744439/6554632/3a6ac350-c65e-11e4-98bd-733938a52310.png)

**Comment by lalindqv** [comment]
Ser bra ut. Frågan är omman inte skulle göra hela sökresultat klickbara (och inte bara rubriken)  enligt detta exempel. Gäller förstås även SFSer: 
![klickbart resultat](https://cloud.githubusercontent.com/assets/9251555/6554771/86fc1010-c65f-11e4-88fa-83946d5a34cc.PNG)

**Comment by kamidev** [comment]
@lalindqv: pröva ovanstående igen.

**Comment by helelun** [comment]
Vid sökning på synonym som leder till SFS blir det mycket gulmarkerat:
![gult synonym](https://cloud.githubusercontent.com/assets/6142669/6641344/7960414c-c99d-11e4-8c81-e2ad4f3afd7b.png)

**Comment by helelun** [comment]
Och så här ser det ut vid sökning på synonym som associerar med ett annat ord. Notera att i tredje träffen på SFS är inte äktenskapsskillnad gulmarkerat i rubriken.

![gult synonymord](https://cloud.githubusercontent.com/assets/6142669/6641501/67130230-c99e-11e4-8a35-a7a63dc1ee67.png)

**Comment by cheijken** [comment]
Lösningen finns med i **feature/383_new_elastic_changes**.

**Comment by lalindqv** [comment]
Krav 54: Träfflistan visar för varje träff och oavsett dokumenttyp rubrik, beteckning, skapat av, utdrag ur texten med sökbegreppet markerat ...

Kravet behöver inte ändras. Tagg specification kan tas bort.

**Comment by kamidev** [comment]
Verifierat på test.lagrummet.se och demo.lagrummet.se. Bra nog för en beta-release.

**Comment by lalindqv** [comment]
OK. 
Frågan är om att "äktenskapskillnader" inte markeras är ett fel. Det ordet kanske inte matchas mot "äktenskapsskillnad" och då är det helt rätt eller en frågan om att ställa elasticiteten.
