### ISSUE TITLE
Sökning på synonym till konsoliderad version av förordning visas ej först

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#404]

**Comment by kamidev** [comment]
Se även #369 och #257

**Comment by lalindqv** [comment]
Helene:
Jag söker på studieledighetslagen vilket är inlagt som synonym till Lag om arbetstagares rätt till ledighet för utbildning (1974:981). 
Förväntat resultat är att konsoliderad version av den lagen kommer upp som första träff. (Jämför demo).
I Viktor hittar jag den bland alla 9440 träffar men inte ens på de 10 första sidorna (sedan gav jag upp).

![404](https://cloud.githubusercontent.com/assets/9251555/6551696/12eeb14a-c63d-11e4-9961-70fc00c4a35a.png)

**Comment by lalindqv** [comment]
NOtering: Om man söker på "Lag om arbetstagares rätt till ledighet för utbildning" får man träff. Lagen presenteras först.

**Comment by helelun** [comment]
Fungerar nu som förväntat på Viktor.

![synonym](https://cloud.githubusercontent.com/assets/6142669/6736648/654a05b2-ce66-11e4-950d-b4ed5a33f34b.png)

**Comment by kamidev** [comment]
Verifierad på test och demo

**Comment by lalindqv** [comment]
Ser bra ut. Ärendet borde kunna stängas.
![sl](https://cloud.githubusercontent.com/assets/9251555/6804134/4f8f0072-d23c-11e4-8531-fd6c65fa7f08.PNG)
