### ISSUE TITLE
Duplikat visas i träfflista

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#405]

**Comment by lalindqv** [comment]
Sökord:                              mig 2014:20
Kommentar:                      Träfflistan visar 3 resultat
                                            Rättsfall (2) indikerar att det eg är två träffar.
                                            Träff 1 och 2 är vad jag kan se ”indentiska”. 

![405](https://cloud.githubusercontent.com/assets/9251555/6552455/4640c5a2-c646-11e4-95be-2ea5061f62cb.PNG)

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#167

**Comment by lalindqv** [comment]
Verkar OK
Duplikat på "uppehållsrum" visas inte längre, se problembeskrivning rinfo/rdl#167, där man kan se "visar 1-17 av 13 träffar.

Har testat att söka på bussförare, lokförare, förgiftning, maffia, torped, kartell, underhuggare, kriminell krets.
Alla ger distiska träffresultat.

**Comment by evajerr** [comment]
Testade samma fråga igen och nu fungerar antalet. 
(Dock dök ett nytt fel upp som jag skapar en ny felrapport för. Sökningen hittar inte mig-referat om de skrivs med små bokstäver vilket funkar för sfs)

![ri github 405 1](https://cloud.githubusercontent.com/assets/9693918/6664574/5ee8c8c6-cbd1-11e4-9942-38a088882f8b.PNG)

**Comment by lalindqv** [comment]
Vilket GitHub-nummer har den felrapporten ?  RDL/lagrummet ?

Med vänlig hälsning
Lars Lindqvist
Konsult, Testledare, Enheten för kommunikationskanaler, Domstolsverket
072-501 76 91 • lars.lindqvist@dom.se • Postadress: 551 81 Jönköping • Besöksadress: Kyrkogatan 34 • Fax: 036-16 57 21 • www.domstol.se<http://www.domstol.se/>


Från: evajerr [mailto:notifications@github.com]
Skickat: den 16 mars 2015 11:42
Till: rinfo/lagrummet.se
Kopia: Lindqvist Lars - DOV
Ämne: Re: [lagrummet.se] Duplikat visas i träfflista (#405)


Testade samma fråga igen och nu fungerar antalet.
(Dock dök ett nytt fel upp som jag skapar en ny felrapport för. Sökningen hittar inte mig-referat om de skrivs med små bokstäver vilket funkar för sfs)

[ri github 405 1]<https://cloud.githubusercontent.com/assets/9693918/6664574/5ee8c8c6-cbd1-11e4-9942-38a088882f8b.PNG>

**Comment by lalindqv** [comment]
Fungerar som det ska.
