### ISSUE TITLE
Referat ska sorteras högre än mål

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#406]

**Comment by lalindqv** [comment]
Eva: 
Sökord: förhandsavgörande arbetsdomstolen
Först presenteras/listas alla målnummer (och man kommer till den tråkiga sidan som bara fyller en funktion när referat saknas?)

Därefter, en bra bit ner, presenteras dito referat (den intressanta informationen).  Jag antar att man är mest intresserad av referaten och de borde i så fall komma först i listningen.

Detta är alltså fel:
![406](https://cloud.githubusercontent.com/assets/9251555/6552602/bdc5d1b6-c647-11e4-86aa-a87d9d34fffd.PNG)

**Comment by jeldeklint** [comment]
den här hör också hemma i `rinfo/rdl`

**Comment by kamidev** [comment]
Sök på text som förekommer i mål/avgöranden och se hur resultet blir. Hur sorteras sökresultatet? 

Ta gärna fram flera bra exempel på önskat utfall! @helelun, @jeldeklint?

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#174

**Comment by evajerr** [comment]
OK. Ser bra ut. Referat kommer först och högst upp i träfflistan. Längre ner i listan är det lite blandat referat - målnummer.
