### ISSUE TITLE
Rätta tester så att de fungerar med ny sökfunktionaltet 

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#407]
Vissa tester fungerar inte på feature-branch. Måste fixas innan vi går tillbaka till develop.

**Comment by kamidev** [comment]
Vi bör även fundera över nya tester för ny sökfunktionaltitet. Hanteras i eget ärende.

**Comment by cheijken** [comment]
Har bortmarkerat 2 tester *test/regression/VA_malummer_exists.js* & *test/regression/VA_search_beteckning.js* för att jag uppfattar dessa tester som korrekta enligt @helelun tidigare instruktioner om hur sökningen skall fungera och vilka träffresultat som förväntas.
Jag är osäker på hur vi förhåller oss till detta i milstolpe 2.2, men jag tror vi behöver ta ställning till om dessa tester är att betrakta som korrekta.

**Comment by kamidev** [comment]
Bygger och går igenom alla regressionstester vid installation på demo.lagrummet.se.
