### ISSUE TITLE
Förenkla befintlig presentationskod

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#408]
Rensa bort icke-använd och/eller irrelevant funktionalitet.

**Comment by cheijken** [comment]
Klar. Lösningen finns i feature/383_new_elastic_changes.
https://github.com/rinfo/lagrummet.se/commit/af221c65383da505aa4570232dd65749928e3bfb
https://github.com/rinfo/lagrummet.se/commit/f1225f1ab65424d7056db5421d6ca34792980103
https://github.com/rinfo/lagrummet.se/commit/1945689dd1f6419f600f84eb08f8241aae8d8818
