### ISSUE TITLE
För många träffar på kategoriserade sökresultaten för redaktionellt material på lagrummet

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/lagrummet.se#409]
Går att få fler än 4 resultat för redaktionellt material i det _kategoriserade_ sökresultatet.
(att den visar 0 träffar är också en känd bugg)
![image](https://cloud.githubusercontent.com/assets/579622/6599689/7c3697ec-c80b-11e4-8979-25d2b46d152e.png)

**Comment by cheijken** [comment]
Lösninge finns i **feature/383_new_elastic_changes**

**Comment by kamidev** [comment]
Lösningen finns nu även på develop. Verifierat på test.lagrummet.se och demo.lagrummet.se.

**Comment by lalindqv** [comment]
Ser OK ut
Visar inte "visa fler" om färre än 4 träffar.
Visar inte "visar 0 träffar".
