### ISSUE TITLE
Hittar inte referat på MÖD via målnummer (i textmassan)

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#416]
Söker ett referat via målnummer (i textmassan) på Miljööverdomstolen.
Hittar inte referatet .

![ri mod 1](https://cloud.githubusercontent.com/assets/9693918/6685294/d5e3edd0-cc98-11e4-8d50-e3c63d5fcda6.PNG)
![ri mod 2](https://cloud.githubusercontent.com/assets/9693918/6685295/d5e67028-cc98-11e4-8bcb-f9228eb53733.PNG)

**Comment by jeldeklint** [comment]
Har delvis hittat varför, har att göra med hur datan kommer in tillsammans med tokenisering av radbrytningar
rätt tydligt i den här skärmdumpen:
![image](https://cloud.githubusercontent.com/assets/579622/6687705/9fdd617a-ccad-11e4-8f1b-a9b3de903e4b.png)
Där det är tydligt att "08" sitter ihop med "Tillstånd" detta blir en token och eftersom det är `AND` mellan termer får man inte trätt på både "m5256" och "08", eftersom den känner till "m5256" och "08Tillstånd".
hur det kommer sig med storbokstav måste jag gräva lite mer i

**Comment by jeldeklint** [comment]
Jag får förövrigt inte träff med varken stor eller liten bokstav, det är inte så att sökningen går iväg när du bytt stor mot liten bokstav?

**Comment by jeldeklint** [comment]
Förövrigt samma problem som i #415 Kan åtgärda det genom att låta den hitta saker som liknar målnummer och behandla dem som en token. alternativt be den splitta på byte mellan tecken / siffra också - vilket tydligen inte är standard

**Comment by jeldeklint** [comment]
Att texten blir som den blir har antagligen mde att göra hur [Apache Tika](http://tika.apache.org/) hanterar den tabelldata DV skickar

**Comment by jeldeklint** [comment]
jag håller på och labbar med en fix för det här

**Comment by cheijken** [comment]
Kommer inte bli klar i 2.2. Flyttar till 2.3

**Comment by jeldeklint** [comment]
Bör vara löst i.o.m rinfo/rdl#180

**Comment by cheijken** [comment]
Sökning på "ville" med sökord "M5256-08" korrekt träff. Sen nedan. Stänger.
![sokning pa mod trafflista](https://cloud.githubusercontent.com/assets/2744439/7112610/9c22df1e-e1cb-11e4-90df-caadcfbf70c6.png)

**Comment by lalindqv** [comment]
Verkar fungera fint.
Har testat följande målnummer. Samtliga ger träff
M5256-08
B4967-12
Ö880-13
T264-12
X9999-09

**Comment by evajerr** [comment]
Har testat mål från Svea HR och hittar referaten via målnummer
ÖÄ11443-12
T10241-12
