### ISSUE TITLE
Regression i TinyMCE ?

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#424]
Har det gjorts någon miss i bygget av 2.2.10 ?  

Underliggande fel:
I Valle  (v2.2.10 ) har:
- den blå-röda linjen halkat ner 
- curson syns ej. Går ej att skriva förrän
- man klickat exakt vid pilen. Då framträder curson och det går att skriva.
![tmce2](https://cloud.githubusercontent.com/assets/9251555/6797482/d7a1f332-d202-11e4-9bcd-757fffd9193e.PNG)

Som jämförelse ( v.0.8.7):
Curson är framme och jag kan börja skriva text direkt.
![tmce1](https://cloud.githubusercontent.com/assets/9251555/6797480/d0784ca0-d202-11e4-8df0-08a512ebb3f1.PNG)

Problemet i sig är inte bra, men går ju enkelt att kunna runt om man känner till det.
Värre är om vi har en regression, som jag tycker bör undersökas närmare i såfall vad den beror på.

**Comment by cheijken** [comment]
Inkört i *release/2.2*

**Comment by kamidev** [comment]
Finns för test på ville, valle och viktor.

**Comment by lalindqv** [comment]
OK
