### ISSUE TITLE
Sökfunktionen på Valle är nere

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#425]
Vad än söker på får jag ett 500-fel:

![500](https://cloud.githubusercontent.com/assets/9251555/6797893/ddf40ac2-d207-11e4-9f4a-a9750791877e.PNG)

Detta stoppar förstås testningen.

**Comment by cheijken** [comment]
Startat om varnish. @jeldeklint byggt om elasticsearch index.
