### ISSUE TITLE
Listvyn kan innehålla hela dokumenttexter

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#427]
Sök tex på "lektronisk kommunikation"
Klicka på "Lagar och förordningar (329)"
Klicka på "Visa alla"
Scrolla ner till tex "Växtförädlingrättslag" ( finns fler exempel längre ner i träfflistan).
Hela dokumentet tycks visas.

Felet uppkommer också om man istället för att klicka "Visa alla" klickar Nästa, Nästa,...

![ek](https://cloud.githubusercontent.com/assets/9251555/6802634/616c8062-d232-11e4-82f0-d166c1416e91.PNG)

**Comment by cheijken** [comment]
Felet ligger i RDL. Bör flyttas dit. @kamidev

**Comment by kamidev** [comment]
Kan du förtydliga på vilket sätt felet ligger i RDL? D v s...  hur återskapar vi felet där? Felrapporten innehåller ett tydligt sätt att stänga ärendet. Har vi något lika tydligt om jag flyttar det till RDL?

**Comment by cheijken** [comment]
En bild säger mer än tusen ord. :) Sökning på "elektronisk kommunikation" på service demo.
![sokning pa elektronisk kommunikation pa service demo](https://cloud.githubusercontent.com/assets/2744439/7112433/ba6a7614-e1c9-11e4-984d-3b442babfd7e.png)

**Comment by cheijken** [comment]
Enligt krav så skall det visas en träffa på max 150 bokstäver. Den andra träffen är inte korrekt.

**Comment by kamidev** [comment]
OK. Jag flyttar... :-)

**Comment by kamidev** [comment]
This issue was moved to rinfo/rdl#197
