### ISSUE TITLE
Beta banner har ofullständig referens

### ISSUE THREAD

**Issue by karejonssondov** [rinfo/lagrummet.se#431]
På sidan 

https://beta.lagrummet.se/om-webbplatsen/kakor

finns href "om-webbplatsen/kakor"

Enklaste länkhanteringen konkatenerar detta till  

https://beta.lagrummet.se/om-webbplatsen/om-webbplatsen/kakor

vilket inte är bäst! Href-en borde vara "/om-webbplatsen/kakor".

**Comment by karejonssondov** [comment]
https://github.com/rinfo/lagrummet.se/commit/1f3daf12d33844a43112b0f77a918082a2ea2268

Verifierat på Stage.

**Comment by kamidev** [comment]
Den här borde vara fixad! Men låt oss verifiera och stänga den.

**Comment by evajerr** [comment]
@kamidev kollar detta innan kodfrys.

**Comment by kamidev** [comment]
Verifierat på test.
