### ISSUE TITLE
Meddelande om att "Only secure content is displayed".

### ISSUE THREAD

**Issue by lalindqv** [rinfo/lagrummet.se#433]
Får ett meddelande om att "Only secure content is displayed".

![ransonering](https://cloud.githubusercontent.com/assets/9251555/6959539/8615dc1c-d91a-11e4-9e94-5e0c769e93fc.PNG)

Meddelandet kommer upp på varje sida jag besöker på betan, även fast jag klickar på "Show all content" .
Meddelandet kommer inte upp på www.lagrummet.se,  felet gäller bara beta.lagrummet.se

Det går inte att återskapa problemet genom att använda Browserstack, vare sig via funktionen "screenshots" eller "live".

Har testat Chrome och Firefox, men liknande meddelande visar sig inte.

Det handlar förmodligen om en säkerhets-inställning i min broswer. 

Allt fungerar som det ska, även om jag INTE klickar "Show all contenet"
Men det är klart irriterande att få upp meddelandet hela tiden.

**Comment by cheijken** [comment]
Misstänker att det är readspeaker som spökar. Vi använder inte en https version av den komponenten. Det behöver åtgärdas.

--------------------------------------------------------------------
<script src="http://f1.eu.readspeaker.com/script/5329/rs_embhl_v2_sv_se.js" type="text/javascript"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	    <script src="/js/application.js" type="text/javascript"></script>

**Comment by kamidev** [comment]
Vi borde generellt ta en titt på att vi inte använder http istället för https.
