### ISSUE TITLE
Uppdatera till JDK 8

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#434]
På sikt är detta nödvändigt för att få aktuella säkerhetsuppdateringar. 

Grails och Groovy (i de versioner vi använder för lagrummet.se) ska redan kompatibla med JDK 8. Men givetvis måste uppdateringen testas ordentlig. 

Notera dock att det inte är lika lätta uppdatera även RDL. Där använder vi en äldre Groovy-version än JDK 8 kräver och det finns kända tekniska svårigheter med att uppgradera. Se #https://github.com/rinfo/rdl/issues/27

**Comment by evajerr** [comment]
Kontrollera att rätt JDK används vid installation. Bör framgå av "Installationsmanuskript", se #441

**Comment by kamidev** [comment]
Fungerar som väntat på test.lagrummet.se om man uppdaterar till OpenJDK 1.8 och bygger om manuellt. Vi kan stänga den här när vi installerat testmiljön enligt manus.

**Comment by kamidev** [comment]
Testmiljön är fastställd till test.lagrummet.se för denna release. 

Arbete med installationsmanus pågår men vi kan tills vidare bygga release-branchen på testmaskinen. Stänger det här ärendet.

**Comment by kamidev** [comment]
I samband med detta genomfördes även punktuppgraderingar av Groovy och Grails.
