### ISSUE TITLE
Granska hur lagrummet fungerar med IE 11

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#438]
Utgå från befintliga regressionstest och gör en manuell granskning.

**Comment by kamidev** [comment]
Kontrollera att detta täcks av automatiserade regressionstester (se https://github.com/rinfo/lagrummet_test. Verifiera med @evajerr att det går att göra en manuell kontroll kontroller via BrowserStack.

**Comment by evajerr** [comment]
Det finns automattester för IE11. Återstår manuell verifiering. Görs av Eva.

**Comment by evajerr** [comment]
Körde igenom alla menyer på lagrummet.se i browserstack IE11. Gjorde också en sökning. Verkar OK men väldigt segt. Kunde inte köra browserstack via firefox.
