### ISSUE TITLE
Förändra startsidelayout för betan

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#443]
Förändra startsida för att ytterligare framhäva att det finns en betasajt med ny sökfunktionalitet.

**Comment by kamidev** [comment]
Se bifogade önskemål om skarpa sidan:

![lagrummet-start_skarpa_2015](https://cloud.githubusercontent.com/assets/1655/10240190/3f30c40c-68d9-11e5-98ac-50516e6c4a24.png)

![lagrummet-start_skarpa_2015_sizes](https://cloud.githubusercontent.com/assets/1655/10240198/481224a8-68d9-11e5-9a7c-674e660d7c20.png)

**Comment by kamidev** [comment]
Önskad förändring av betans startsida:

![lagrummet-start_beta_2015](https://cloud.githubusercontent.com/assets/1655/10240258/df52d772-68d9-11e5-8acd-9fa6ccae0d67.png)

![lagrummet-start_beta_2015_sizes](https://cloud.githubusercontent.com/assets/1655/10240260/e52ab0ac-68d9-11e5-8350-bdf0a8447369.png)

**Comment by kamidev** [comment]
Se även kommentarerna från @helelun i ärende #452 och #453.

**Comment by helelun** [comment]
Klick på betaloggan ska resultera i att man är kvar på betasajten. Klickar man från en undersida på betan ska man komma till betans startsida.

**Comment by kamidev** [comment]
Ändringar incheckade på develop. Installerat på ville, test och demo. Klarar alla automattester via https://github.com/rinfo/lagrummet_test.

**Comment by helelun** [comment]
Kommenterar från Ville som nu gäller som nya betan.
1. Aktuell startsidetext inlagd. (Hade inte följt med från Stage som tidigare speglade beta).
2. Önskemål att få ett litet avstånd mellan texten och puffarna, jämför startsidan på Valle.
3. Kolla för säkerhets skull att rätt css ligger på startsidan. Ser rätt ut för ögat men i admin ser jag att IE9-fix ligger i koden. (Jfr kommentar i layout skarpa startsidan).

**Comment by kamidev** [comment]
CSS kontrollerad enligt ovan. Lite mer luft inlagd under presenterande text (notera att detta är en redaktionell ändring som just nu bara finns på ville.lagrummet.se.

**Comment by evajerr** [comment]
Startsidan i Ville ser inte ut som ovanstående beskrivning av nya betasöksidan.
Både texter och grafik avviker. Om något är ändrat men inte kommunicerat till mej vet jag inte. Måste därför felrapportera detta.

![fel betasidan 443](https://cloud.githubusercontent.com/assets/9693918/11528383/9d2bd456-98e6-11e5-8879-1ffccd497161.PNG)

**Comment by helelun** [comment]
Vi har valt att ta bort stora tomma ytan mellan text och puffar. 
Övrigt är redaktionellt innehåll vilket inte var något som behandlades i spec:en. 
Stänger ärendet utan åtgärd.
