### ISSUE TITLE
Dokumentera och uppdatera vid behov manuella regressionstester

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#445]
Vilka tester är fortfarande lämpliga att göra manuellt i samband med testfasen inför en ny release? Fundera över vilket mervärde de manuella testerna har jämfört de automatiserade.

**Comment by helelun** [comment]
Readspeaker bör fungera på samma sätt på nya skarpa och på nya betan efter release av 2.4. Jag är oklar om du Eva kan testa detta i förväg eller om det måste ske efter release. 
OBS! Just nu fungerar inte readspeaker alls på varken skarpa eller betan. Se annat issue om detta.
