### ISSUE TITLE
Förändra layout för sökresultat

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#448]

**Comment by kamidev** [comment]
Önskad förändring av sökresultatet:

![lagrummet-sokresultat-beta](https://cloud.githubusercontent.com/assets/1655/10240244/c185dd48-68d9-11e5-9fc7-b661e5b6ee80.png)

![lagrummet-sokresultat-beta-sizes](https://cloud.githubusercontent.com/assets/1655/10240245/c6d5337a-68d9-11e5-8649-903ea974116c.png)

**Comment by Leome** [comment]
Merged into #443

**Comment by helelun** [comment]
Kommentar från dagens möte:
* Ta bort den gamla texten om sökhjälp som ligger under den blå plattan.
* Ta bort den blå rutan runt sökfältet som dyker upp när man klickar i sökfältet (gäller sökfältet på samtliga sidor).

**Comment by kamidev** [comment]
Ändringar incheckade på develop. Installerat på ville, test och demo. Klarar alla automattester via https://github.com/rinfo/lagrummet_test.

**Comment by evajerr** [comment]
Blå rutan på Ville ser inte likadan ut som ovan. Vet inte heller hur "ta bort gamla texten om sökhjälp" ska ändras.

Nu ser blårutan i sökresultatet ut så här.

![fel pa soksidan 448](https://cloud.githubusercontent.com/assets/9693918/11528644/5a02b27e-98e8-11e5-9d43-c95655f4665c.PNG)

**Comment by helelun** [comment]
Innehållet i blå rutan är redaktionellt och var inte korrekt i spec:en.
Gamla texten om sökhjälp låg tidigare under blå rutan. Den är redan borttagen.
