### ISSUE TITLE
Förändra startsidelayout för www.lagrummet.se

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#449]
Förändra startsidan för att ytterligare framhäva att det finns en betasajt med ny sökfunktionalitet.

**Comment by kamidev** [comment]
Önskad förändring av den skarpa startsidan:

![lagrummet-start_skarpa_2015](https://cloud.githubusercontent.com/assets/1655/10240190/3f30c40c-68d9-11e5-98ac-50516e6c4a24.png)

![lagrummet-start_skarpa_2015_sizes](https://cloud.githubusercontent.com/assets/1655/10240198/481224a8-68d9-11e5-9a7c-674e660d7c20.png)

**Comment by kamidev** [comment]
@helelun kommer att komplettera med redaktionell text (se ärende #451).

**Comment by helelun** [comment]
Kommentarer från dagens möte:
* Blå rutan som pekar till betan (stage) ska endast ligga på startsidan. Inte på några underliggande sidor.
* Cookie-bannern ska ligga på nya skarpa.
* När cookie-bannern klickas bort ska det inte vara "luft" kvar ovanför sajtens färgade överlinje. 
* Css ska ändras för den redaktionella texten på startsidan (typsnitt, centrerad första rubrik men ej centrerad text.

**Comment by kamidev** [comment]
Funktionellt klar. Uppdatera testerna så att söktester inte körs mot www.lagrummet.se (som för närvarande inte ska ska ha sökning).

**Comment by helelun** [comment]
Rubriken Vad är lagrummet.se? följer inte spec. Ändras i css, jag kan inte påverka i admin.

**Comment by helelun** [comment]
Bredden på texten följer inte spec som visar att texten ska vara lika bred som blå rutan.
Detta är i nuläget av lägre prioritet.

**Comment by kamidev** [comment]
Rubrik ändrad till Trebuchet. Kan testas på ville.lagrummet.se

**Comment by kamidev** [comment]
Skapat nytt ärende för att hantera felaktig textbredd: #475

**Comment by kamidev** [comment]
Den senaste version fanns inte på valle.lagrummet.se. Testa igen!

**Comment by helelun** [comment]
Nu ser det riktigt ut! Jag stänger.

**Comment by evajerr** [comment]
Kör i Valle och ser att texten i blå rutan inte är vänsterjusterad på rad 2.

Ser också ett antal avvikelser från bilden ovan.

![fel skarpa 449](https://cloud.githubusercontent.com/assets/9693918/11528886/c3754662-98e9-11e5-93a5-82eae3042014.PNG)

**Comment by helelun** [comment]
Släpper att texten i blå rutan inte är vänsterjusterad.
Övrigt är redaktionellt innehåll som inte var relevant i spec:en.
Stänger ärendet utan åtgärd.
