### ISSUE TITLE
Uppdatera texten på förstasidan lagrummet.se

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#451]

**Comment by helelun** [comment]
Var kan jag göra detta? Använder stage för uppdateringar i nya betan.

**Comment by helelun** [comment]
Uppdateringar för skarpa sker från och med idag på Valle.

**Comment by karejonssondov** [comment]
Titta på artiklarna. Jag tror det är hårdkodade länkar i materialet.

Rättsinformation – rättskällorna
Myndigheters och kommuners ansvar
Om lagrummet.se
Kakor (cookies)

Med vänlig hälsning
Kåre Jonsson
Systemutvecklare, IT-avdelningen, Enheten för systemkonstruktion, Domstolsverket
036-44 22 118 • 0730-25 26 00 • kare.jonsson@dom.se • Postadress: Box 2113, 103 13 Stockholm • Besöksadress: Torsgatan 11 • www.domstol.se<http://www.domstol.se/>
www.lagrummet.se<http://www.lagrummet.se/>



Från: helelun [mailto:notifications@github.com]
Skickat: den 20 oktober 2015 09:11
Till: rinfo/lagrummet.se
Ämne: Re: [lagrummet.se] Uppdatera texten på förstasidan lagrummet.se (#451)


Uppdateringar för skarpa sker från och med idag på Valle.

**Comment by helelun** [comment]
Texten på startsidan uppdaterad.

Notera nya kommentarer om layout i #449.

Blå rutan pekar nu till "skarpa" betan. Under test bör den väl peka mot Ville? Pekningen är hårdkodad och kan inte ändras i admin.

**Comment by kamidev** [comment]
Jag föreslår att den blå rutan får fortsätta att peka dit den ska "på riktigt". Annars krånglar vi till test och release-processen.
