### ISSUE TITLE
Uppdatera texten på sidor med sökresultat beta.lagrummet.se

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#453]
Se till att beskrivande text och länkar till sidor med med mer information är uppdaterade.

**Comment by helelun** [comment]
Sökresultatsidan är inte redigerbar via admin.
Lägg in texten nedan i den blå rutan när den är skapad:

------------Text----------------
/rubrik/ Vad tycker du om vår nya söktjänst? /slut rubrik/
Mejla gärna dina synpunkter till feedback@lagrummet.se!
/obs. särskild kod för hur denna länk ska skrivas. Se betans kontaktsida./

/rubrik/ Hittade du inte vad du sökte? /slut rubrik/
Gå till vår sökhjälp.   /länk = http://stage.lagrummet.se/sokhjalp/
------------Slut text----------------

**Comment by kamidev** [comment]
Stänger denna. @Leome lägger in det som inte går att lägga in via admin.

**Comment by helelun** [comment]
Kommentar utifrån Ville:
Texten i blå rutan längst ned på sökresultatsidorna är inte i enlighet med vad jag angett ovan att texten ska vara! Notera också att det är fel ordning på några ord i rubriken. 

OBS särskild kod för hur mejladressen ska skrivas.

**Comment by helelun** [comment]
Redigerad text blå rutan: 

------------Text----------------
/rubrik/ Vad tycker du om vår nya söktjänst? /slut rubrik/
Mejla gärna dina synpunkter på söktjänsten till betafeedback@lagrummet.se!
Hittade du inte vad du sökte? Gå till vår sökhjälp. 
------------Slut text----------------

(Länkar betafeedback och sökhjälp se mitt inlägg ovan 7/10).

**Comment by kamidev** [comment]
Blå ruta med ändrad kan testas på ville.lagrummet.se.

**Comment by helelun** [comment]
Text ok. Länkarna fungerar.
