### ISSUE TITLE
Lista redaktionell text som skiljer sig mellan lagrummet.se och beta.lagrummet.se

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#454]

**Comment by kamidev** [comment]
@Leome och @helelun: vi tittar närmare på om den här listan behövs vi är igång med #449 och  #451.

**Comment by helelun** [comment]
Sidor som skiljer sig mellan nya skarpa (Valle) och nya beta (Ville):
* Startsidan
* Alla rättskällor
* Sökhjälp (ska endast finnas på Ville. Är nu avpublicerad på Valle). 
* Kontakta oss (olika texter. Ville ska eventuellt uppdateras med besked om när datat är insamlat).

Länkuppdateringar etc. sker alltid på dagens skarpa och oftast även på dagens beta. När vi växlar över är det databasen från skarpa som gäller.

**Comment by kamidev** [comment]
Vad är skillnaden vad gäller rättskällor?

**Comment by helelun** [comment]
På redaktionella sidan "Alla rättskällor" skiljer sig texten något mellan skarpa och beta. Dessutom visar betan vilka rättskällor som är sökbara. Sistnämnda styrs genom funktionen hantera rättskällor i admin.
