### ISSUE TITLE
Uppdatera engelsk informationssida

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#456]
Se till att innehållet fungerar för betan.

**Comment by kamidev** [comment]
Är denna som den ska vara på stage just nu? Eller bör den ses över ett varv till? Ping @helelun.

**Comment by helelun** [comment]
Engelska sidan är nu uppdaterad på Ville så att samma version ligger där som på Valle. Det är samma version som idag också ligger på skarpa sajten.
