### ISSUE TITLE
Hittar inte "allt" vid sökning på synonym

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#459]
Miljö: Stage
Söker på äktenskapsskillnad och får Lagar och Förordningar (110)
Söker sedan på skillsmässa och får Lagar och Förordningar (84)

Hade förväntat mej samma. Absolut inte färre.

![aktenskapsskillnad](https://cloud.githubusercontent.com/assets/9693918/10602448/a54cb8fc-7718-11e5-9199-7176899eecd1.PNG)

![skilsmassa](https://cloud.githubusercontent.com/assets/9693918/10602497/ee0bb14c-7718-11e5-9fc5-b8511dbddac7.PNG)

**Comment by karejonssondov** [comment]
Skilsmässa är en synonym som pekar på "äktenskapsskillnad". När man söker på "skilsmässa" för man sökresultaten på skilsmässa + resultaten på äktenskapsskillnad. När man söker på "äktenskapsskillnad" bara just det. Skillnanden är de fall där ordet skilsmässa förekommer vilket inte är noll, enligt bilden. Det är alltså algoritmen som är förklaringen. 

Huruvida denna förväntan är rimlig eller ej kan diskuteras. Möjligtvis är förväntan driven av kännedomen om det interna förfarandet med synonymer.

Motfrågor: Skulle du förvänta dig samma antyal träffar på

LAS <--> Lagen om anställningsskydd
LVU <--> Lagen om vård av unga
studieledighetslagen <--> Lag om arbetstagares rätt till ledighet för utbildning (1974:981)

och så vidare.

**Comment by evajerr** [comment]
Då borde det inte bli färre utan samma eller ev fler när man tittar på Lagar och Förordningar där jag antar att man INTE använder ordet skilsmässa. 
Jag pratar INTE om Rättsfallen.

**Comment by karejonssondov** [comment]
Undersöker på beta:

äktenskapsskillnad: Rättsfall 372, lagar och förordningar 110
skilsmässa: Rättsfall 446, lagar och förordningar 89

Nu förstår jag. Rättsfallen beter sig som förväntat men det problem du påvisar framgår i fallet lagar och förordningar.

**Comment by evajerr** [comment]
Just det jag menar Lagar och Förordningar som i synonymfallet borde vara åtminstone 110.
