### ISSUE TITLE
Readspeaker fungerar varken på skarpa sajten eller på betan

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#460]
Manuella regressionstester (se #445) ska säkerställa att readspeaker/lyssna fungerar på nya skarpa och nya betan efter release 2.4. Men just nu fungerar readspeaker inte alls för mig vare sig på publika skarpa eller på publika betan. 

Sökning på "readspeaker" respektive "lyssna" ger ett antal öppna och stängda issues med koppling till readspeaker. 

Buggen om lyssna på sökresultat kan ligga kvar på senare release.

**Comment by kamidev** [comment]
Vad är status på detta? Kan vi testa redan nu eller gäller eventuella fixar bara för specifika domäner?

**Comment by kamidev** [comment]
Vi har nu checkat in kod och veriferat för hand på test och demo. Den grundläggande funktionaliteten för att läsa upp text bör nu vara funktionell igen. Det återstår en del kända problem, t ex hopp tillbaka till startsidan när man klickar på lyssna.
