### ISSUE TITLE
Leta efter kompatibilitetsproblem med olika webbläsare

### ISSUE THREAD

**Issue by kamidev** [rinfo/lagrummet.se#465]
Vi använder Browserstack och manuell besiktning för att hitta eventuella skillnader mellan webbläsare. Notera och lista upptäckta problem här. Skapa separata ärenden för komplicerade/svårlösta problem. Fixa enklare problem direkt.

**Comment by Leome** [comment]
<img width="743" alt="skarmavbild 2015-10-26 kl 10 19 50" src="https://cloud.githubusercontent.com/assets/2697780/10725286/2851c4de-7bcb-11e5-9611-d7b0993f47cc.png">

Safari 9

**Comment by Leome** [comment]
<img width="514" alt="skarmavbild 2015-10-26 kl 10 24 54" src="https://cloud.githubusercontent.com/assets/2697780/10725359/d764784a-7bcb-11e5-9b6c-759164c18445.png">

Safari 9

**Comment by kamidev** [comment]
Att köra automattester mot Browserstack sker via en separat testapplikation. Se https://github.com/rinfo/lagrummet_test/issues/2.

**Comment by kamidev** [comment]
Nödvändig grundfunktionalitet finns för denna release. Stänger detta ärende och hänvisar till rinfo/lagrummet_test vid fortsatt utveckling.
