### ISSUE TITLE
Rätt adminversion till nya skarpa?

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#467]
Noterar att Valle, som speglar skarpa, inte har samma adminversion som dagens skarpa. Hoppas att det inte följer med efter release vilket innebär en del retsamma buggar som nu endast finns i beta?

**Comment by kamidev** [comment]
Se även #468.

**Comment by kamidev** [comment]
Vi har varken arbetat med eller testat admin alls under release 2.4. Så buggar som funnits i beta men inte i dagens skarpa kvarstår.

**Comment by helelun** [comment]
Buggarna tar vi hand om senare. Ärendet gäller att nya skarpa inte plötsligt får en annan admin än nuvarande skarpa.

**Comment by helelun** [comment]
Fick vid december-releasen acceptera att betans admin också blev skarpa sajtens admin. Buggar i admin hanteras i andra issues i senare releaser. Stänger denna utan vidare åtgärd.
