### ISSUE TITLE
Text i redaktörsfältet i admin/skarpa/English breder ut sig utanför marginalen

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#468]
Noterade just att i admin för skarpa saknas buggfixen som hindrar att texten breder ut sig utanför högermarginalen.

Se #306.

**Comment by kamidev** [comment]
Ingen admin-kod har ändrats i denna version. Vi har inte tagit höjd för att testa någon admin-funktionalitet i denna release.

**Comment by helelun** [comment]
Stänger då ärendet är inaktuellt. Kommer att hanteras i senare release för beta-admin.
