### ISSUE TITLE
Blå rutan längst ned i sökresultat slår inte igenom när man går från kategoriserad till listvy

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#470]
Sökresultat visas i första steget i den kategoriserade träfflistan. Längst ned finns en blå ruta där vi bland annat bjuder in användarna till att lämna synpunkter på söket. (Uppdatering av texten i rutan se #453). 

Väljer man att gå ett steg till i sökresultatet för att se fler träffar inom en viss kategori kommer man till listvyn. Där saknas blå rutan. I stället ligger gamla hänvisningen kvar.

**Comment by kamidev** [comment]
Efter dagens möte prioriterar vi ner det här. Görs endast i mån av tid men i så fall före #306. 

Får det inte plats inom ramen för release 2.4 flyttar vi ärendet till nästa.

**Comment by helelun** [comment]
Även om blå rutan sker i nästa release måste själva texten uppdateras i denna. (Ligger utanför admin). Ändra nuvarande text till att exakt motsvara det som ska stå i blå rutan.

**Comment by kamidev** [comment]
Att uppdatera den texten ligger redan i ärende #453 och har högre prioritet.

**Comment by kamidev** [comment]
Blå ruta tillagd. Med efterfrågad ny text

**Comment by helelun** [comment]
Text och länkar ok. 

Saknar mellanrum mellan antalet sidor med träffar och blå rutans överkant.
![blarutanlistvyn](https://cloud.githubusercontent.com/assets/6142669/11183356/816859e6-8c71-11e5-9203-2c079a08adda.PNG)

**Comment by kamidev** [comment]
Skapar nytt ärende för felet ovan: #470
