### ISSUE TITLE
Kvarvarande IE9 kod

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#473]
IE9 kod ligger överst på startsidorna i admin skarpa, beta och Ville. Har förmodligen själv raderat det på Valle. Inga andra sidor än startsidorna verkar vara berörda. 

![kodvillestart](https://cloud.githubusercontent.com/assets/6142669/11186724/5e9596b0-8c83-11e5-9ac9-21f06c0f543a.PNG)

**Comment by kamidev** [comment]
Tog bort de IE9-specifika fixarna från sidmallarna. Vi väntar med att ändra i befintliga redaktionella sidor tills efter nästa release.

**Comment by kamidev** [comment]
Fundera över om det är nödvändigt att gå igenom befintliga redaktionella sidor och ändra detta. Kanske räcker det att nya sidor eller ändrade sidor blir rätt?

**Comment by helelun** [comment]
IE9-koden finns kvar på beta och test (och övriga som speglar betan). IE9-koden ligger endast på startsidorna.
IE9-koden var en fix för att hantera en bug som gjorde att första bokstaven i text på startsidan, som då hade ett för startsidan tillfälligt typsnitt, ramlade bort för IE9-användare. Så vitt jag minns fanns det typsnittet endast på skarpa och borde inte fylla någon funktion alls på dagens beta?

**Comment by helelun** [comment]
Tidigare incheckad mallkod innebär att kodsnutten för IE9 inte kommer att återkomma. Stänger ärendet utan vidare åtgärd.
