### ISSUE TITLE
"Hittar inte sidan" vid Publicering av befintlig sida

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#478]
Testmiljö Viktor

Går in på en befintlig sida: Rättspraxis.
Ändrar texten sparar Utkast och väljer Publicera (onsdag 18/11)

Fredag 20/11: Går in för att upprepa felet.
Kan inte återskapa felet. Däremot har det känts buggigt och jag har blivit utslängd ett antal gånger. Detta kanske också är ett sådant fel??

![andrar rattspraxix](https://cloud.githubusercontent.com/assets/9693918/11245199/c841ef34-8e11-11e5-9258-3d95ca595b30.PNG)

![sidan kan intye visas](https://cloud.githubusercontent.com/assets/9693918/11245209/cfdcb062-8e11-11e5-969a-97b7310cbf7c.PNG)

**Comment by helelun** [comment]
Spontan kommentar är att redaktör inte skulle välja att spara text som är färdig att publiceras som ett utkast. (Var det så du gjorde när du testade? I så fall är det kanske inte så konstigt att det inte fungerade). Arbetssättet skulle sannolikt vara att skapa en ny sida med ett framtida datum och samtidigt lägga ett publicera till datum på den sida som sedan inte längre ska gälla.

**Comment by evajerr** [comment]
2015-12-07: Denna felrapport diskuterades på dagens go/nogo-möte. Jag skulle kolla igen om det går att framkalla felet. 
Jag har gjort ett antal uppdateringar (i Viktor och Ville) men inte lyckats få Sidan kan inte visas. Jag stänger därför denna felrapport.
