### ISSUE TITLE
Sidan flyttar sej i vänstermenyn vid Publicera/Uppdatera

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#479]
Skapa en ny sida.
Lägger/drar ner den en bit i vänstermenyn under Myndigheters föreskrifter
Väljer spara utkast
När jag väljer att Publicera det så åker den upp i vänstermenyn.

Spara utkast

![ny sida2](https://cloud.githubusercontent.com/assets/9693918/11266855/f1c6dee6-8ea7-11e5-89fa-a26b9255049c.PNG)

Publicera

![ny sida 2 publicerad](https://cloud.githubusercontent.com/assets/9693918/11266860/fc41a644-8ea7-11e5-8d7d-dbc5a1113587.PNG)

Samma fel om jag gör så här:

Skapa en ny sida.
Väljer Publicera
Lägger/drar ner den en bit i vänstermenyn under Myndigheters föreskrifter
När jag väljer att Uppdatera så åker den upp i vänstermenyn.

Den säger att "En annan användare har uppdaterat sidan" har ingen relevans. Varför ?? Detta gjorde jag inom loppet av några minuter.

**Comment by helelun** [comment]
Sidornas placering i trädet styrs, om jag minns rätt, av bokstavsordning. Redaktör som vill påverka placeringen använder fältet Sorteringsordning.
Detta är alltså inte en bug så jag stänger ärendet.
