### ISSUE TITLE
Får olika feedback-mailadresser före och efter enter

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#484]
Testmiljö Ville, 2.4

Anger ett sökord UTAN att trycka enter och får upp blåa feedbackrutan med fel mailadress (hej robot)
om jag väljer den så ser den helt konstig ut.
Om jag gör samma sökning som ovan och trycker ENTER. Kickar därefter på mailadressen (betafeedback@...) och får då rätt mailadress ifylld. 

FÖRE enter
![hej robot](https://cloud.githubusercontent.com/assets/9693918/11555030/69e0209a-999d-11e5-8ec8-0b7d1ac026d8.PNG)

![grekisk mailadress](https://cloud.githubusercontent.com/assets/9693918/11555036/70dfa898-999d-11e5-873d-7c8b6a7024dc.PNG)

EFTER enter

![betafeedback](https://cloud.githubusercontent.com/assets/9693918/11555046/8da6b886-999d-11e5-9ee8-fe6f6584380e.PNG)

![mailadress betafeedback](https://cloud.githubusercontent.com/assets/9693918/11555055/9b1f1be8-999d-11e5-810a-e46a6facee48.PNG)

**Comment by kamidev** [comment]
Fix incheckad: 736602a704503f4255b69e041cfb5e369ace9e5e. 

Checka ut och installera release/2.4 för att testa.

**Comment by helelun** [comment]
Korrekt resultat är så som Evas bilder ovan EFTER enter visar.

**Comment by evajerr** [comment]
Testad på Ville av Eva 2015-12-07. 
I båda lägena visas rätt mailadress (betafeedback@lagrummet.se) som en länk.
