### ISSUE TITLE
Fel mailadress (Valle och Ville)  på engelska sidan när man kör Lyssna

### ISSUE THREAD

**Issue by evajerr** [rinfo/lagrummet.se#485]
Valle (=skarpa) och Ville (=beta)

På engelska sidan BLIR det fel mailadress Hej robot när man kör Lyssna

![hej robot valle](https://cloud.githubusercontent.com/assets/9693918/11584053/9b742584-9a60-11e5-92f7-2320b1b33100.PNG)

![valle 2](https://cloud.githubusercontent.com/assets/9693918/11584054/a1674688-9a60-11e5-9d84-d804ec61b9df.PNG)

**Comment by kamidev** [comment]
Löses enklast genom ändring av det redaktionella innehållet.

**Comment by helelun** [comment]
Har bytt ut länkade mejladressen mot en olänkad på både ville och valle. Vill vi redigera adressen ytterligare kan det göras efter release.

**Comment by evajerr** [comment]
Testad på Valle 2015-12-07 av Eva.
OK
