### ISSUE TITLE
Cookiebannern har fel adress på skarpa

### ISSUE THREAD

**Issue by helelun** [rinfo/lagrummet.se#486]
Detta gäller skarpa sajten: Cookiebannern högst upp på varje sida innehåller länken Om kakor och hur vi använder dem. Länkadressen är fel. Bannern kan inte redigeras av redaktör.

Rätt adress är:
https://lagrummet.se/om-webbplatsen/kakor

**Comment by karejonssondov** [comment]
Fixat!

**Comment by kamidev** [comment]
Funkar från extern adress. :-)
